// File: questions.js
const questionBank = [
    // --- MÔN TOÁN (Số học, Hình học, Đo lường) ---
    {
        "q": "Số gồm '5 trăm nghìn, 7 chục và 6 đơn vị' được viết là:",
        "a": ["500076", "500706", "570006", "5000706"],
        "c": 0
    },
    {
        "q": "Góc nhỏ hơn góc vuông được gọi là góc gì?",
        "a": ["Góc tù", "Góc bẹt", "Góc nhọn", "Góc vuông"],
        "c": 2
    },
    {
        "q": "Trung bình cộng của hai số là 25. Biết một trong hai số là 30. Số còn lại là bao nhiêu?",
        "a": ["20", "25", "5", "55"],
        "c": 0
    },
    {
        "q": "Kết quả của phép tính 125 x 8 là:",
        "a": ["100", "1000", "1258", "800"],
        "c": 1
    },
    {
        "q": "2 tấn 50 kg đổi ra ki-lô-gam bằng bao nhiêu?",
        "a": ["250 kg", "2500 kg", "2050 kg", "20050 kg"],
        "c": 2
    },
    {
        "q": "Thế kỷ XXI bắt đầu từ năm nào?",
        "a": ["Năm 2000", "Năm 2001", "Năm 2100", "Năm 1900"],
        "c": 1
    },
    {
        "q": "Trong các số sau, số nào chia hết cho cả 2 và 5?",
        "a": ["234", "985", "1050", "3006"],
        "c": 2
    },
    {
        "q": "Hình bình hành có tính chất nào sau đây?",
        "a": ["Bốn góc đều là góc vuông", "Hai cặp cạnh đối diện song song và bằng nhau", "Bốn cạnh bằng nhau", "Chỉ có một cặp cạnh song song"],
        "c": 1
    },

    // --- MÔN TIẾNG VIỆT (Đọc hiểu, Luyện từ và câu) ---
    {
        "q": "Trong câu 'Chú mèo mướp nằm sưởi nắng bên thềm nhà', bộ phận nào là chủ ngữ?",
        "a": ["Chú mèo", "Chú mèo mướp", "Nằm sưởi nắng", "Bên thềm nhà"],
        "c": 1
    },
    {
        "q": "Từ nào dưới đây là từ láy?",
        "a": ["Xanh tươi", "Mặt đất", "Lung linh", "Nhà cửa"],
        "c": 2
    },
    {
        "q": "Câu 'Chao ôi! Bông hoa hồng mới đẹp làm sao!' thuộc kiểu câu gì?",
        "a": ["Câu kể", "Câu hỏi", "Câu khiến", "Câu cảm"],
        "c": 3
    },
    {
        "q": "Biện pháp nghệ thuật nào được sử dụng trong câu: 'Bác Mặt Trời đạp xe qua đỉnh núi'?",
        "a": ["So sánh", "Nhân hóa", "Điệp từ", "Đảo ngữ"],
        "c": 1
    },
    {
        "q": "Thành ngữ nào dưới đây nói về lòng nhân ái?",
        "a": ["Thương người như thể thương thân", "Học thầy không tày học bạn", "Một nắng hai sương", "Chân cứng đá mềm"],
        "c": 0
    },
    {
        "q": "Danh từ riêng trong câu 'Sông Bạch Đằng đã đi vào lịch sử hào hùng của dân tộc' là:",
        "a": ["Sông", "Bạch Đằng", "Lịch sử", "Dân tộc"],
        "c": 1
    },
    {
        "q": "Dấu ngoặc kép trong câu thường dùng để làm gì?",
        "a": ["Ngăn cách các vế câu", "Kết thúc câu", "Đánh dấu lời nói trực tiếp hoặc từ ngữ đặc biệt", "Biểu thị sự liệt kê"],
        "c": 2
    },

    // --- MÔN KHOA HỌC ---
    {
        "q": "Thành phần nào trong không khí quan trọng nhất đối với sự hô hấp của con người?",
        "a": ["Khí Ni-tơ", "Khí Các-bô-nic", "Khí Ô-xi", "Hơi nước"],
        "c": 2
    },
    {
        "q": "Vật nào dưới đây tự phát sáng?",
        "a": ["Mặt Trăng", "Mặt Trời", "Tấm gương", "Trái Đất"],
        "c": 1
    },
    {
        "q": "Để bảo vệ nguồn nước, chúng ta KHÔNG nên làm gì?",
        "a": ["Xử lý rác thải trước khi xả", "Tiết kiệm nước", "Vứt rác bừa bãi xuống sông hồ", "Tuyên truyền bảo vệ môi trường"],
        "c": 2
    },
    {
        "q": "Nấm có vai trò gì trong tự nhiên?",
        "a": ["Làm thức ăn và phân hủy xác sinh vật", "Chỉ gây hại cho cây trồng", "Cung cấp khí ô-xi", "Làm cảnh"],
        "c": 0
    },
    {
        "q": "Động vật cần những yếu tố nào để sống?",
        "a": ["Chỉ cần thức ăn", "Không khí, nước, thức ăn, ánh sáng, nhiệt độ thích hợp", "Chỉ cần nước uống", "Chỉ cần ánh sáng"],
        "c": 1
    },
    {
        "q": "Âm thanh KHÔNG thể truyền qua môi trường nào?",
        "a": ["Chất rắn", "Chất lỏng", "Chất khí", "Chân không"],
        "c": 3
    },

    // --- MÔN LỊCH SỬ & ĐỊA LÝ ---
    {
        "q": "Vùng đất Tây Nguyên có đặc điểm địa hình chính là gì?",
        "a": ["Đồng bằng châu thổ rộng lớn", "Các cao nguyên xếp tầng", "Vùng núi cao hiểm trở nhất nước", "Vùng biển đảo"],
        "c": 1
    },
    {
        "q": "Lễ hội Cồng chiêng là nét văn hóa đặc sắc của vùng nào?",
        "a": ["Đồng bằng Bắc Bộ", "Tây Nguyên", "Nam Bộ", "Duyên hải miền Trung"],
        "c": 1
    },
    {
        "q": "Kinh đô của nước Văn Lang đặt tại đâu?",
        "a": ["Phong Châu (Phú Thọ)", "Cổ Loa (Hà Nội)", "Hoa Lư (Ninh Bình)", "Thăng Long (Hà Nội)"],
        "c": 0
    },
    {
        "q": "Vị tướng nào đã lãnh đạo nhân dân ta đánh tan quân Nam Hán trên sông Bạch Đằng năm 938?",
        "a": ["Lý Thường Kiệt", "Trần Hưng Đạo", "Ngô Quyền", "Đinh Bộ Lĩnh"],
        "c": 2
    },
    {
        "q": "Đồng bằng sông Hồng được bồi đắp bởi phù sa của hệ thống sông nào?",
        "a": ["Sông Mê Kông và sông Đồng Nai", "Sông Hồng và sông Thái Bình", "Sông Mã và sông Cả", "Sông Thu Bồn"],
        "c": 1
    },
    {
        "q": "Địa đạo Củ Chi là di tích lịch sử nổi tiếng thuộc thành phố nào?",
        "a": ["Hà Nội", "Đà Nẵng", "TP. Hồ Chí Minh", "Cần Thơ"],
        "c": 2
    },

    // --- MÔN CÔNG NGHỆ / TIN HỌC (Cơ bản) ---
    {
        "q": "Khi ngồi làm việc với máy tính, mắt nên cách màn hình khoảng bao nhiêu?",
        "a": ["10 - 20 cm", "50 - 80 cm", "Trên 1 mét", "Càng gần càng tốt"],
        "c": 1
    },
    {
        "q": "Loại hoa nào thường được chưng vào dịp Tết ở miền Nam?",
        "a": ["Hoa Đào", "Hoa Mai", "Hoa Phượng", "Hoa Sen"],
        "c": 1
    },
    // --- BẮT ĐẦU GÓI 30 CÂU: CÁC SỐ ĐẾN LỚP TRIỆU ---
    {
        "q": "Số 'Hai mươi triệu' được viết như thế nào?",
        "a": ["2 000 000", "20 000 000", "200 000 000", "20 000"],
        "c": 1
    },
    {
        "q": "Lớp triệu gồm những hàng nào?",
        "a": ["Hàng triệu, hàng trăm nghìn, hàng chục nghìn", "Hàng triệu, hàng chục triệu, hàng trăm triệu", "Hàng nghìn, hàng chục nghìn, hàng trăm nghìn", "Hàng trăm triệu, hàng chục triệu, hàng triệu, hàng trăm"],
        "c": 1
    },
    {
        "q": "Số 15 000 000 đọc là gì?",
        "a": ["Mười năm triệu", "Mười lăm triệu", "Một trăm năm mươi triệu", "Mười lăm nghìn"],
        "c": 1
    },
    {
        "q": "Trong số 145 302 000, chữ số 4 thuộc hàng nào?",
        "a": ["Hàng triệu", "Hàng chục triệu", "Hàng trăm triệu", "Hàng nghìn"],
        "c": 1
    },
    {
        "q": "Số gồm 5 trăm triệu, 7 triệu, 3 trăm nghìn và 2 đơn vị viết là:",
        "a": ["507 300 002", "570 300 002", "507 030 002", "57 300 002"],
        "c": 0
    },
    {
        "q": "10 trăm nghìn bằng bao nhiêu?",
        "a": ["100 000", "1 000 000 (1 triệu)", "10 000 000 (10 triệu)", "100 000 000"],
        "c": 1
    },
    {
        "q": "Giá trị của chữ số 8 trong số 38 402 510 là:",
        "a": ["800 000", "8 000 000", "80 000", "8 000"],
        "c": 1
    },
    {
        "q": "Số liền sau của số 999 999 là số nào?",
        "a": ["999 998", "1 000 000", "1 000 001", "10 000 000"],
        "c": 1
    },
    {
        "q": "Số nào dưới đây lớn nhất?",
        "a": ["9 876 543", "12 000 000", "11 999 999", "9 999 999"],
        "c": 1
    },
    {
        "q": "Số 300 000 000 có bao nhiêu chữ số 0?",
        "a": ["6", "7", "8", "9"],
        "c": 2
    },
    {
        "q": "Các chữ số thuộc lớp nghìn trong số 205 341 678 là:",
        "a": ["2, 0, 5", "3, 4, 1", "6, 7, 8", "1, 4, 3"],
        "c": 1
    },
    {
        "q": "Số liền trước của số 10 000 000 là:",
        "a": ["9 999 999", "9 000 000", "10 000 001", "99 999 999"],
        "c": 0
    },
    {
        "q": "Dãy số nào sau đây được sắp xếp theo thứ tự từ bé đến lớn?",
        "a": ["5 000 000; 4 999 999; 6 000 000", "1 200 000; 1 300 000; 1 250 000", "10 000; 100 000; 1 000 000", "900 000; 1 000 000; 999 999"],
        "c": 2
    },
    {
        "q": "Số chẵn liền sau của số 2 000 000 là:",
        "a": ["2 000 001", "2 000 002", "2 000 003", "1 999 999"],
        "c": 1
    },
    {
        "q": "Viết số: Bảy trăm linh năm triệu, ba mươi nghìn.",
        "a": ["705 030 000", "750 030 000", "705 300 000", "705 003 000"],
        "c": 0
    },
    {
        "q": "Số nào dưới đây có chữ số hàng chục triệu là 5?",
        "a": ["530 000 000", "350 000 000", "305 000 000", "53 000 000"],
        "c": 1
    },
    {
        "q": "Một triệu có mấy lớp?",
        "a": ["1 lớp", "2 lớp", "3 lớp", "4 lớp"],
        "c": 2
    },
    {
        "q": "Chữ số 9 trong số 192 000 000 có giá trị là bao nhiêu?",
        "a": ["9 triệu", "90 triệu", "900 triệu", "900 nghìn"],
        "c": 1
    },
    {
        "q": "Kết quả của phép cộng: 3 000 000 + 500 000 + 20 là:",
        "a": ["3 500 020", "3 050 020", "3 500 200", "352 000"],
        "c": 0
    },
    {
        "q": "Trong dãy số tự nhiên, hai số liên tiếp hơn kém nhau bao nhiêu đơn vị?",
        "a": ["2 đơn vị", "1 đơn vị", "10 đơn vị", "5 đơn vị"],
        "c": 1
    },
    {
        "q": "Số bé nhất có 7 chữ số là:",
        "a": ["1 000 000", "1 111 111", "1 023 456", "9 999 999"],
        "c": 0
    },
    {
        "q": "Số lớn nhất có 8 chữ số khác nhau là:",
        "a": ["99 999 999", "98 765 432", "98 765 430", "10 234 567"],
        "c": 1
    },
    {
        "q": "Lớp đơn vị của số 45 678 912 gồm các chữ số nào?",
        "a": ["4, 5", "6, 7, 8", "9, 1, 2", "1, 2"],
        "c": 2
    },
    {
        "q": "Điền số thích hợp vào chỗ chấm: 30 000 000, 40 000 000, ..., 60 000 000",
        "a": ["45 000 000", "50 000 000", "55 000 000", "5 000 000"],
        "c": 1
    },
    {
        "q": "Số 605 000 000 đọc là:",
        "a": ["Sáu trăm linh năm triệu", "Sáu trăm năm mươi triệu", "Sáu mươi lăm triệu", "Sáu trăm linh năm nghìn"],
        "c": 0
    },
    {
        "q": "Trong các số sau, số nào là số lẻ?",
        "a": ["12 000 000", "45 678 222", "9 876 541", "100 000 008"],
        "c": 2
    },
    {
        "q": "Chữ số 0 trong số 140 567 892 nằm ở hàng nào?",
        "a": ["Hàng triệu", "Hàng chục triệu", "Hàng trăm nghìn", "Hàng trăm triệu"],
        "c": 0
    },
    {
        "q": "Làm tròn số 12 567 000 đến hàng triệu, ta được:",
        "a": ["12 000 000", "13 000 000", "10 000 000", "12 500 000"],
        "c": 1
    },
    {
        "q": "Viết số thích hợp: 4 triệu = ... trăm nghìn.",
        "a": ["4", "40", "400", "4000"],
        "c": 1
    },
    {
        "q": "Số gồm '3 trăm triệu và 3 đơn vị' viết là:",
        "a": ["300 000 003", "300 300 300", "303 000 000", "33"],
        "c": 0
    },
    // --- GÓI 30 CÂU: PHÉP CỘNG, TRỪ & BIỂU THỨC CÓ CHỨA CHỮ ---
    { "q": "Giá trị của biểu thức 15 + a với a = 5 là bao nhiêu?", "a": ["10", "15", "20", "25"], "c": 2 },
    { "q": "Nếu a = 10 và b = 2 thì giá trị của a - b là:", "a": ["8", "12", "5", "20"], "c": 0 },
    { "q": "Biểu thức nào dưới đây là biểu thức có chứa một chữ?", "a": ["15 + 20", "a + 5", "a + b", "x + y - z"], "c": 1 },
    { "q": "Tính giá trị của biểu thức m x 3 với m = 6:", "a": ["9", "3", "18", "2"], "c": 2 },
    { "q": "Công thức tính chu vi hình vuông cạnh a là:", "a": ["a x a", "a x 4", "a + 4", "a : 4"], "c": 1 },
    { "q": "Với a = 100, b = 50, giá trị của biểu thức a + b là:", "a": ["100", "50", "150", "1500"], "c": 2 },
    { "q": "Tính chất giao hoán của phép cộng được viết dạng tổng quát là:", "a": ["a + b = a - b", "a + b = b + a", "a + b = b - a", "(a + b) + c = a + (b + c)"], "c": 1 },
    { "q": "Tìm x biết: x + 235 = 500", "a": ["x = 265", "x = 735", "x = 275", "x = 365"], "c": 0 },
    { "q": "Giá trị của biểu thức a + b + c với a=5, b=10, c=15 là:", "a": ["20", "25", "30", "35"], "c": 2 },
    { "q": "Kết quả của phép tính 123 456 + 456 123 là:", "a": ["579 579", "579 589", "569 579", "589 579"], "c": 0 },
    { "q": "Trong biểu thức a - (b + c), nếu a=50, b=10, c=5 thì kết quả là:", "a": ["35", "45", "55", "25"], "c": 0 },
    { "q": "Phép tính 25 + 48 + 75 có thể tính nhanh bằng cách:", "a": ["(25 + 48) + 75", "(25 + 75) + 48", "25 + (48 + 75)", "Lấy 75 trừ 25 rồi cộng 48"], "c": 1 },
    { "q": "Biểu thức có chứa ba chữ là:", "a": ["a + b", "a + b + 5", "a + b + c", "10 + 20 + 30"], "c": 2 },
    { "q": "Tìm x biết: 800 - x = 350", "a": ["x = 450", "x = 1150", "x = 550", "x = 350"], "c": 0 },
    { "q": "Tổng của hai số là 100, hiệu của hai số là 20. Số lớn là:", "a": ["40", "60", "80", "50"], "c": 1 },
    { "q": "Tính giá trị của P = m + n x 2 với m = 10, n = 5:", "a": ["30", "20", "75", "25"], "c": 1 },
    { "q": "Tính chất kết hợp của phép cộng là:", "a": ["a + b = b + a", "(a + b) + c = a + (b + c)", "a + 0 = a", "a x 1 = a"], "c": 1 },
    { "q": "Kết quả của phép trừ 1 000 000 - 99 là:", "a": ["999 901", "900 001", "1 000 099", "999 001"], "c": 0 },
    { "q": "Tìm một số biết số đó cộng với 150 thì bằng 400:", "a": ["550", "250", "350", "200"], "c": 1 },
    { "q": "Với m = 8, biểu thức 100 - m x 5 có giá trị là:", "a": ["460", "60", "500", "90"], "c": 1 },
    { "q": "Hình chữ nhật có chiều dài a, chiều rộng b. Công thức tính chu vi P là:", "a": ["P = a x b", "P = a + b x 2", "P = (a + b) x 2", "P = a + b"], "c": 2 },
    { "q": "Một cửa hàng ngày đầu bán được a kg gạo, ngày sau bán được b kg. Tổng số gạo bán được là:", "a": ["a - b", "a x b", "a : b", "a + b"], "c": 3 },
    { "q": "Cho biểu thức A = 500 - (100 + x). Khi x tăng thì giá trị của A sẽ:", "a": ["Tăng lên", "Giảm đi", "Không đổi", "Gấp đôi"], "c": 1 },
    { "q": "Tổng của hai số chẵn liên tiếp là 50. Hai số đó là:", "a": ["24 và 26", "23 và 27", "20 và 30", "25 và 25"], "c": 0 },
    { "q": "Kết quả của 325 + 0 bằng:", "a": ["0", "325", "3250", "32"], "c": 1 },
    { "q": "Phép trừ nào sau đây có kết quả bằng 0?", "a": ["a - 0", "a + 0", "a - a", "0 - a"], "c": 2 },
    { "q": "Tổng của số lớn nhất có 4 chữ số và số bé nhất có 4 chữ số là:", "a": ["10 999", "19 999", "9 999", "8 999"], "c": 0 },
    { "q": "Tìm hiệu của hai số, biết số bị trừ là 24 000 và số trừ là 4 000:", "a": ["28 000", "20 000", "6", "96 000"], "c": 1 },
    { "q": "Nếu a + b = 100 thì (a + 10) + b bằng bao nhiêu?", "a": ["100", "90", "110", "120"], "c": 2 },
    { "q": "Tính giá trị của a x (b + c) với a=2, b=3, c=7:", "a": ["13", "20", "17", "21"], "c": 1 },
    // --- GÓI 30 CÂU: PHÉP NHÂN, CHIA & HÌNH HỌC CƠ BẢN ---
    { "q": "Kết quả của phép nhân 125 x 10 là:", "a": ["1250", "1205", "1025", "12500"], "c": 0 },
    { "q": "Góc bẹt bằng mấy lần góc vuông?", "a": ["1 lần", "2 lần", "3 lần", "4 lần"], "c": 1 },
    { "q": "Hai đường thẳng vuông góc với nhau tạo thành mấy góc vuông?", "a": ["1", "2", "3", "4"], "c": 3 },
    { "q": "Tính nhẩm: 25 x 4 x 7 =", "a": ["70", "700", "1400", "7000"], "c": 1 },
    { "q": "Trong phép chia có dư, số dư lớn nhất có thể có là:", "a": ["Bằng số chia", "Lớn hơn số chia", "Kém số chia 1 đơn vị", "Bằng 0"], "c": 2 },
    { "q": "Góc lớn hơn góc vuông và nhỏ hơn góc bẹt là góc gì?", "a": ["Góc nhọn", "Góc tù", "Góc vuông", "Góc tròn"], "c": 1 },
    { "q": "Hình chữ nhật có các cặp cạnh đối diện như thế nào?", "a": ["Vuông góc với nhau", "Song song và bằng nhau", "Cắt nhau", "Không song song"], "c": 1 },
    { "q": "Tìm x biết: x : 5 = 120", "a": ["x = 24", "x = 600", "x = 60", "x = 500"], "c": 1 },
    { "q": "Biểu thức a x (b + c) bằng biểu thức nào dưới đây?", "a": ["a x b + c", "a x b + a x c", "a + b x c", "a x b x c"], "c": 1 },
    { "q": "Kết quả của phép tính 200 : 100 là:", "a": ["20", "2", "200", "10"], "c": 1 },
    { "q": "Số trung bình cộng của 10, 20 và 30 là:", "a": ["15", "20", "25", "30"], "c": 1 },
    { "q": "Để tính diện tích hình chữ nhật, ta thực hiện:", "a": ["(Dài + Rộng) x 2", "Dài x Rộng", "Dài + Rộng", "Cạnh x Cạnh"], "c": 1 },
    { "q": "1 yến bằng bao nhiêu ki-lô-gam?", "a": ["10 kg", "100 kg", "1000 kg", "1 kg"], "c": 0 },
    { "q": "Hai đường thẳng song song là hai đường thẳng:", "a": ["Không bao giờ cắt nhau", "Cắt nhau tại 1 điểm", "Tạo thành góc vuông", "Trùng nhau"], "c": 0 },
    { "q": "Phép chia 75 : 5 có kết quả là:", "a": ["13", "14", "15", "16"], "c": 2 },
    { "q": "Tính giá trị biểu thức: 10 + 20 x 3", "a": ["90", "70", "60", "50"], "c": 1 },
    { "q": "Đơn vị đo diện tích nào lớn hơn m2?", "a": ["dm2", "cm2", "mm2", "km2"], "c": 3 },
    { "q": "Số thích hợp điền vào chỗ chấm: 3 tấn 50kg = ... kg", "a": ["350 kg", "3050 kg", "3500 kg", "30050 kg"], "c": 1 },
    { "q": "Trong các góc sau, góc nào có số đo bằng 90 độ?", "a": ["Góc nhọn", "Góc tù", "Góc vuông", "Góc bẹt"], "c": 2 },
    { "q": "Một hình vuông có cạnh là 5cm. Chu vi hình vuông đó là:", "a": ["20 cm", "25 cm", "10 cm", "15 cm"], "c": 0 },
    { "q": "Phép nhân 34 x 11 có kết quả là:", "a": ["374", "341", "433", "3434"], "c": 0 },
    { "q": "Tính chất kết hợp của phép nhân là:", "a": ["a x b = b x a", "(a x b) x c = a x (b x c)", "a x 1 = a", "a x (b + c)"], "c": 1 },
    { "q": "Trung bình cộng của hai số là 50. Tổng của hai số đó là:", "a": ["25", "50", "100", "150"], "c": 2 },
    { "q": "3 giờ bằng bao nhiêu phút?", "a": ["120 phút", "150 phút", "180 phút", "300 phút"], "c": 2 },
    { "q": "Thương của phép chia số tròn chục cho 10 là:", "a": ["Số đó thêm một chữ số 0", "Số đó bớt đi một chữ số 0", "Số đó giữ nguyên", "Số đó nhân với 10"], "c": 1 },
    { "q": "Hình nào dưới đây có 4 góc vuông và 4 cạnh bằng nhau?", "a": ["Hình chữ nhật", "Hình bình hành", "Hình vuông", "Hình thoi"], "c": 2 },
    { "q": "Nếu tích hai số là 0 thì:", "a": ["Cả hai số phải bằng 0", "Ít nhất một trong hai số bằng 0", "Không số nào bằng 0", "Số lớn phải bằng 0"], "c": 1 },
    { "q": "Một thế kỷ bằng bao nhiêu năm?", "a": ["10 năm", "50 năm", "100 năm", "1000 năm"], "c": 2 },
    { "q": "Tìm số chia biết: Số bị chia = 100, Thương = 5.", "a": ["20", "500", "95", "105"], "c": 0 },
    { "q": "Đổi đơn vị: 5m2 8dm2 = ... dm2", "a": ["58 dm2", "508 dm2", "580 dm2", "5008 dm2"], "c": 1 },
    { "q": "Kết quả của phép cộng 235 + 460 là:", "a": ["595", "685", "695", "705"], "c": 2 },
    { "q": "Kết quả của phép trừ 900 - 475 là:", "a": ["425", "435", "415", "445"], "c": 0 },
    { "q": "Kết quả của phép nhân 125 x 10 là:", "a": ["1250", "1205", "1025", "12500"], "c": 0 },
    { "q": "Kết quả của phép chia 840 : 7 là:", "a": ["100", "110", "120", "130"], "c": 2 },
    { "q": "Tổng của 345 và 255 là:", "a": ["500", "590", "600", "610"], "c": 1 },
    { "q": "Hiệu của 800 và 345 là:", "a": ["445", "455", "465", "475"], "c": 1 },
    { "q": "Kết quả của phép nhân 48 x 5 là:", "a": ["180", "200", "220", "240"], "c": 3 },
    { "q": "Kết quả của phép chia 600 : 3 là:", "a": ["150", "175", "200", "250"], "c": 2 },
    { "q": "Tổng của 1200 và 350 là:", "a": ["1450", "1500", "1550", "1600"], "c": 0 },
    { "q": "Hiệu của 1500 và 675 là:", "a": ["725", "825", "875", "925"], "c": 0 },

    { "q": "Kết quả của 32 x 4 là:", "a": ["96", "108", "112", "128"], "c": 0 },
    { "q": "Kết quả của 420 : 6 là:", "a": ["60", "65", "70", "75"], "c": 2 },
    { "q": "Kết quả của 250 + 375 là:", "a": ["525", "600", "625", "650"], "c": 2 },
    { "q": "Kết quả của 900 - 365 là:", "a": ["535", "545", "555", "565"], "c": 0 },
    { "q": "Kết quả của 56 x 3 là:", "a": ["148", "156", "158", "168"], "c": 1 },
    { "q": "Kết quả của 810 : 9 là:", "a": ["80", "85", "90", "95"], "c": 2 },
    { "q": "Tổng của 625 và 275 là:", "a": ["800", "850", "875", "900"], "c": 1 },
    { "q": "Hiệu của 700 và 285 là:", "a": ["405", "415", "425", "435"], "c": 0 },
    { "q": "Kết quả của 67 x 2 là:", "a": ["124", "134", "144", "154"], "c": 1 },
    { "q": "Kết quả của 720 : 8 là:", "a": ["70", "80", "85", "90"], "c": 1 },

    { "q": "Kết quả của 345 + 150 là:", "a": ["465", "475", "485", "495"], "c": 2 },
    { "q": "Kết quả của 1000 - 425 là:", "a": ["545", "555", "565", "575"], "c": 0 },
    { "q": "Kết quả của 23 x 5 là:", "a": ["105", "110", "115", "120"], "c": 2 },
    { "q": "Kết quả của 960 : 6 là:", "a": ["140", "150", "155", "160"], "c": 0 },
    { "q": "Tổng của 780 và 125 là:", "a": ["885", "895", "905", "915"], "c": 2 },
    { "q": "Hiệu của 1300 và 650 là:", "a": ["600", "620", "650", "700"], "c": 2 },
    { "q": "Kết quả của 42 x 4 là:", "a": ["148", "158", "168", "178"], "c": 2 },
    { "q": "Kết quả của 540 : 9 là:", "a": ["50", "55", "60", "65"], "c": 2 },
    { "q": "Kết quả của 135 + 425 là:", "a": ["540", "550", "560", "570"], "c": 0 },
    { "q": "Kết quả của 800 - 375 là:", "a": ["405", "415", "425", "435"], "c": 2 },
    { "q": "Kết quả của phép cộng 456 + 378 là:", "a": ["824", "834", "844", "854"], "c": 2 },
    { "q": "Kết quả của phép trừ 1000 - 475 là:", "a": ["515", "525", "535", "545"], "c": 2 },
    { "q": "Kết quả của 72 x 5 là:", "a": ["350", "360", "380", "390"], "c": 1 },
    { "q": "Kết quả của 540 : 6 là:", "a": ["70", "80", "85", "90"], "c": 1 },
    { "q": "Tổng của 625 và 340 là:", "a": ["945", "955", "965", "975"], "c": 0 },
    { "q": "Hiệu của 900 và 245 là:", "a": ["635", "645", "655", "665"], "c": 1 },
    { "q": "Kết quả của 36 x 7 là:", "a": ["242", "252", "262", "272"], "c": 1 },
    { "q": "Kết quả của 840 : 7 là:", "a": ["100", "110", "120", "130"], "c": 2 },
    { "q": "Kết quả của 455 + 125 là:", "a": ["560", "570", "580", "590"], "c": 1 },
    { "q": "Kết quả của 700 - 385 là:", "a": ["305", "315", "325", "335"], "c": 1 },
    { "q": "Kết quả của 64 x 4 là:", "a": ["236", "246", "256", "266"], "c": 2 },
    { "q": "Kết quả của 630 : 9 là:", "a": ["60", "65", "70", "75"], "c": 0 },
    { "q": "Kết quả của 245 + 380 là:", "a": ["605", "615", "625", "635"], "c": 2 },
    { "q": "Kết quả của 1500 - 675 là:", "a": ["725", "825", "875", "925"], "c": 0 },
    { "q": "Kết quả của 55 x 6 là:", "a": ["300", "310", "320", "330"], "c": 1 },
    { "q": "Kết quả của 810 : 9 là:", "a": ["80", "85", "90", "95"], "c": 2 },
    { "q": "Tổng của 525 và 275 là:", "a": ["740", "780", "800", "820"], "c": 2 },
    { "q": "Hiệu của 1000 và 485 là:", "a": ["495", "505", "515", "525"], "c": 1 },
    { "q": "Kết quả của 46 x 3 là:", "a": ["118", "128", "138", "148"], "c": 2 },
    { "q": "Kết quả của 720 : 6 là:", "a": ["100", "110", "120", "130"], "c": 2 },
    { "q": "Kết quả của 345 + 260 là:", "a": ["585", "595", "605", "615"], "c": 1 },
    { "q": "Kết quả của 900 - 455 là:", "a": ["435", "445", "455", "465"], "c": 0 },
    { "q": "Kết quả của 28 x 5 là:", "a": ["120", "130", "140", "150"], "c": 2 },
    { "q": "Kết quả của 560 : 8 là:", "a": ["60", "65", "70", "75"], "c": 2 },
    { "q": "Tổng của 415 và 385 là:", "a": ["780", "790", "800", "810"], "c": 0 },
    { "q": "Hiệu của 1400 và 650 là:", "a": ["700", "720", "740", "760"], "c": 0 },
    { "q": "Kết quả của 62 x 4 là:", "a": ["228", "238", "248", "258"], "c": 2 },
    { "q": "Kết quả của 450 : 5 là:", "a": ["80", "85", "88", "90"], "c": 3 },
    { "q": "Kết quả của 235 + 465 là:", "a": ["690", "700", "710", "720"], "c": 1 },
    { "q": "Kết quả của 1000 - 365 là:", "a": ["625", "635", "645", "655"], "c": 2 },
    // 30 câu hỏi Toán lớp 4: Góc nhọn – Góc tù – Đường vuông góc – Đường song song
    { "q": "Góc nào có số đo nhỏ hơn 90°?", "a": ["Góc vuông", "Góc nhọn", "Góc tù", "Góc bẹt"], "c": 1 },
    { "q": "Góc nào có số đo lớn hơn 90° nhưng nhỏ hơn 180°?", "a": ["Góc vuông", "Góc nhọn", "Góc tù", "Góc bẹt"], "c": 2 },
    { "q": "Hai đường thẳng vuông góc tạo thành bao nhiêu góc vuông?", "a": ["1", "2", "3", "4"], "c": 3 },
    { "q": "Hai đường thẳng không bao giờ cắt nhau được gọi là gì?", "a": ["Vuông góc", "Song song", "Trùng nhau", "Cắt nhau"], "c": 1 },
    { "q": "Góc có số đo đúng bằng 90° gọi là gì?", "a": ["Góc nhọn", "Góc tù", "Góc vuông", "Góc bẹt"], "c": 2 },
    { "q": "Một góc nhọn luôn có số đo trong khoảng: ", "a": ["> 0° và < 90°", "= 90°", "> 90° và < 180°", "= 180°"], "c": 0 },
    { "q": "Hai đường thẳng vuông góc tạo với nhau góc bằng:", "a": ["45°", "60°", "90°", "120°"], "c": 2 },
    { "q": "Góc 120° là loại góc gì?", "a": ["Góc nhọn", "Góc tù", "Góc vuông", "Góc bẹt"], "c": 1 },
    { "q": "Góc 45° là loại góc gì?", "a": ["Góc nhọn", "Góc tù", "Góc vuông", "Góc bẹt"], "c": 0 },
    { "q": "Để kiểm tra hai đường thẳng có vuông góc hay không, ta dùng: ", "a": ["Thước thẳng", "Compa", "Ê ke", "Thước dây"], "c": 2 },

    { "q": "Hai đường thẳng luôn cách đều nhau được gọi là: ", "a": ["Vuông góc", "Cắt nhau", "Song song", "Trùng nhau"], "c": 2 },
    { "q": "Góc 180° gọi là gì?", "a": ["Góc vuông", "Góc bẹt", "Góc tù", "Góc nhọn"], "c": 1 },
    { "q": "Góc nào sau đây là góc tù?", "a": ["70°", "89°", "110°", "30°"], "c": 2 },
    { "q": "Góc nào sau đây là góc nhọn?", "a": ["110°", "95°", "70°", "180°"], "c": 2 },
    { "q": "Dấu hiệu nhận biết đường thẳng vuông góc: ", "a": ["Chúng không gặp nhau", "Chúng tạo góc 90°", "Chúng trùng nhau", "Chúng tạo góc 180°"], "c": 1 },
    { "q": "Trong các góc sau, đâu là góc vuông?", "a": ["30°", "45°", "60°", "90°"], "c": 3 },
    { "q": "Nếu hai đường thẳng cắt nhau và tạo một góc vuông, các góc còn lại là: ", "a": ["Góc tù", "Góc nhọn", "Góc vuông", "Góc bẹt"], "c": 2 },
    { "q": "Hai đường thẳng không song song thì: ", "a": ["Chắc chắn vuông góc", "Có thể cắt nhau", "Không bao giờ cắt nhau", "Không xác định"], "c": 1 },
    { "q": "Góc 10° là: ", "a": ["Góc nhọn", "Góc tù", "Góc vuông", "Góc bẹt"], "c": 0 },
    { "q": "Góc 170° là: ", "a": ["Góc tù", "Góc vuông", "Góc nhọn", "Góc bẹt"], "c": 0 },

    { "q": "Hai đường thẳng cắt nhau tạo ra góc 95°. Đây là:", "a": ["Góc nhọn", "Góc tù", "Góc vuông", "Góc bẹt"], "c": 1 },
    { "q": "Một góc vuông được chia đôi tạo thành hai góc: ", "a": ["Góc tù", "Góc nhọn", "Góc vuông", "Góc bẹt"], "c": 1 },
    { "q": "Để vẽ một góc vuông, em cần dùng: ", "a": ["Compa", "Ê ke", "Thước dây", "Thước cong"], "c": 1 },
    { "q": "Góc nào lớn nhất?", "a": ["Góc nhọn", "Góc tù", "Góc vuông", "Góc bẹt"], "c": 3 },
    { "q": "Trong hình, nếu hai cạnh đối diện luôn cách đều nhau, hình đó có cặp cạnh: ", "a": ["Vuông góc", "Cắt nhau", "Song song", "Trùng nhau"], "c": 2 },
    { "q": "Góc 88° thuộc loại góc nào?", "a": ["Góc vuông", "Góc tù", "Góc nhọn", "Góc bẹt"], "c": 2 },
    { "q": "Góc nào sau đây không phải góc tù?", "a": ["120°", "150°", "91°", "89°"], "c": 3 },
    { "q": "Một góc 0° đến 180° được gọi chung là: ", "a": ["Góc bẹt", "Góc phẳng", "Góc nhọn", "Góc tù"], "c": 1 },
    { "q": "Trong văn bản hình học, kí hiệu ⟂ dùng để chỉ: ", "a": ["Song song", "Cắt nhau", "Vuông góc", "Bằng nhau"], "c": 2 },
    { "q": "Nếu hai đường thẳng tạo với nhau góc 45°, đó là: ", "a": ["Góc vuông", "Góc nửa vuông", "Góc nhọn", "Góc tù"], "c": 2 },
    { "q": "Một góc có số đo 20° là góc gì?", "a": ["Góc nhọn", "Góc vuông", "Góc tù", "Góc bẹt"], "c": 0 },
    { "q": "Góc tù là góc có số đo:", "a": ["< 90°", "= 90°", "> 90° và < 180°", "= 180°"], "c": 2 },
    { "q": "Hai đường thẳng vuông góc tạo với nhau một góc:", "a": ["60°", "90°", "120°", "180°"], "c": 1 },
    { "q": "Hai đường thẳng song song là hai đường thẳng:", "a": ["Cắt nhau", "Vuông góc", "Không bao giờ cắt nhau", "Trùng nhau"], "c": 2 },
    { "q": "Một góc có số đo 95° là góc:", "a": ["Nhọn", "Vuông", "Tù", "Bẹt"], "c": 2 },
    { "q": "Một góc vuông có số đo:", "a": ["30°", "60°", "90°", "120°"], "c": 2 },
    { "q": "Góc 15° thuộc loại:", "a": ["Góc nhọn", "Góc vuông", "Góc tù", "Góc bẹt"], "c": 0 },
    { "q": "Góc 160° là:", "a": ["Góc nhọn", "Góc vuông", "Góc tù", "Góc bẹt"], "c": 2 },
    { "q": "Hai đường thẳng có một điểm chung là hai đường:", "a": ["Song song", "Vuông góc", "Cắt nhau", "Không xác định"], "c": 2 },
    { "q": "Hai đường thẳng không có điểm chung và không song song thì:", "a": ["Trùng nhau", "Vuông góc", "Song song", "Không xảy ra"], "c": 3 },
    { "q": "Góc 75° là góc:", "a": ["Nhọn", "Vuông", "Tù", "Bẹt"], "c": 0 },
    { "q": "Một góc có số đo 180° gọi là:", "a": ["Góc nhọn", "Góc vuông", "Góc tù", "Góc bẹt"], "c": 3 },
    { "q": "Hai đường thẳng luôn giữ khoảng cách bằng nhau là:", "a": ["Vuông góc", "Song song", "Cắt nhau", "Trùng nhau"], "c": 1 },
    { "q": "Một góc có số đo 120° là:", "a": ["Nhọn", "Vuông", "Tù", "Bẹt"], "c": 2 },
    { "q": "Hai đường thẳng vuông góc tạo mấy góc vuông?", "a": ["1", "2", "3", "4"], "c": 3 },
    { "q": "Góc 5° thuộc loại:", "a": ["Nhọn", "Vuông", "Tù", "Bẹt"], "c": 0 },
    { "q": "Góc lớn hơn 0° nhưng nhỏ hơn 90° là:", "a": ["Góc tù", "Góc nhọn", "Góc vuông", "Góc bẹt"], "c": 1 },
    { "q": "Một góc 89° là góc:", "a": ["Nhọn", "Vuông", "Tù", "Bẹt"], "c": 0 },
    { "q": "Một góc 91° là góc:", "a": ["Nhọn", "Vuông", "Tù", "Bẹt"], "c": 2 },
    { "q": "Góc 0° được gọi là:", "a": ["Góc không", "Góc nhọn", "Góc tù", "Góc vuông"], "c": 0 },
    { "q": "Hai đường thẳng vuông góc có:", "a": ["Hai góc tù", "Một góc vuông", "Bốn góc vuông", "Không có góc vuông"], "c": 2 },
    { "q": "Góc 170° là:", "a": ["Nhọn", "Vuông", "Tù", "Bẹt"], "c": 2 },
    { "q": "Hai đường thẳng song song:", "a": ["Không cắt nhau", "Giao nhau một điểm", "Vuông góc nhau", "Tạo thành bốn góc vuông"], "c": 0 },
    { "q": "Một góc 30° là:", "a": ["Góc nhọn", "Góc vuông", "Góc tù", "Góc bẹt"], "c": 0 },
    { "q": "Góc có số đo lớn hơn 90° nhưng nhỏ hơn 180° là:", "a": ["Góc nhọn", "Góc vuông", "Góc tù", "Góc bẹt"], "c": 2 },
    { "q": "Một góc có số đo đúng 90° là:", "a": ["Nhọn", "Vuông", "Tù", "Bẹt"], "c": 1 },
    { "q": "Hai đường thẳng trùng nhau có:", "a": ["Không điểm chung", "Một điểm chung", "Vô số điểm chung", "Không xác định"], "c": 2 },
    { "q": "Một góc 179° là:", "a": ["Nhọn", "Vuông", "Tù", "Bẹt"], "c": 2 },
    { "q": "Để kiểm tra hai đường thẳng vuông góc, ta dùng:", "a": ["Thước thẳng", "Compa", "Ê-ke", "Thước dây"], "c": 2 },
    { "q": "Hai đường thẳng song song có thể:", "a": ["Cách đều nhau", "Giao nhau", "Vuông góc", "Trùng nhau"], "c": 0 },
    { "q": "Phân số 4/8 rút gọn được thành:", "a": ["1/4", "1/2", "2/3", "3/4"], "c": 1 },
    { "q": "Phân số 6/9 rút gọn là:", "a": ["2/3", "3/5", "1/2", "4/5"], "c": 0 },
    { "q": "Phân số nào bằng 1/3?", "a": ["2/6", "3/9", "4/12", "Cả 3 đáp án trên"], "c": 3 },
    { "q": "Tử số của phân số 5/7 là:", "a": ["5", "7", "12", "2"], "c": 0 },
    { "q": "Mẫu số của phân số 11/13 là:", "a": ["13", "11", "1", "24"], "c": 0 },
    { "q": "Rút gọn phân số 10/15 được:", "a": ["2/3", "3/5", "4/6", "1/3"], "c": 1 },
    { "q": "Phân số 9/12 rút gọn bằng:", "a": ["2/3", "3/4", "1/2", "3/5"], "c": 0 },
    { "q": "Trong các phân số sau, phân số lớn nhất là:", "a": ["1/5", "2/5", "3/5", "4/5"], "c": 3 },
    { "q": "Quy đồng mẫu số 1/2 và 1/3 ta được:", "a": ["3/6 và 2/6", "2/6 và 3/6", "1/5 và 1/6", "2/3 và 3/2"], "c": 0 },
    { "q": "Phân số nào nhỏ nhất?", "a": ["2/7", "3/7", "4/7", "5/7"], "c": 0 },
    { "q": "So sánh 2/3 và 3/4:", "a": ["2/3 > 3/4", "2/3 < 3/4", "2/3 = 3/4", "Không so sánh được"], "c": 1 },
    { "q": "Phân số 14/21 rút gọn thành:", "a": ["2/3", "3/2", "1/3", "4/7"], "c": 0 },
    { "q": "Quy đồng phân số 3/4 và 5/6 có mẫu số chung:", "a": ["12", "10", "24", "6"], "c": 0 },
    { "q": "Phân số 15/20 rút gọn bằng:", "a": ["3/5", "4/5", "2/3", "1/4"], "c": 0 },
    { "q": "Phân số nào bằng 1/2?", "a": ["5/10", "6/12", "7/14", "Cả 3 đều đúng"], "c": 3 },
    { "q": "So sánh 5/8 và 5/9:", "a": ["5/8 > 5/9", "5/8 < 5/9", "5/8 = 5/9", "Không so sánh được"], "c": 0 },
    { "q": "Quy đồng mẫu số 3/5 và 4/7 ta được:", "a": ["21/35 và 20/35", "9/12 và 16/12", "15/21 và 20/21", "5/7 và 7/5"], "c": 0 },
    { "q": "Rút gọn phân số 18/24:", "a": ["3/4", "4/3", "2/3", "1/4"], "c": 0 },
    { "q": "Phân số nhỏ hơn 1 là:", "a": ["5/5", "8/7", "3/4", "9/8"], "c": 2 },
    { "q": "So sánh 7/9 và 3/4:", "a": ["7/9 > 3/4", "7/9 < 3/4", "Bằng nhau", "Không so sánh được"], "c": 1 },
    { "q": "Phân số 12/18 rút gọn là:", "a": ["1/2", "2/3", "3/4", "4/6"], "c": 1 },
    { "q": "Quy đồng 2/3 và 3/5:", "a": ["10/15 và 9/15", "9/15 và 10/15", "6/9 và 9/15", "5/8 và 8/5"], "c": 0 },
    { "q": "Phân số 8/32 rút gọn được:", "a": ["1/2", "1/3", "1/4", "1/5"], "c": 2 },
    { "q": "So sánh 4/6 và 2/3:", "a": ["4/6 > 2/3", "4/6 < 2/3", "4/6 = 2/3", "Không so sánh được"], "c": 2 },
    { "q": "Phân số lớn hơn 1 là:", "a": ["3/5", "5/3", "1/4", "2/7"], "c": 1 },
    { "q": "Rút gọn phân số 21/35:", "a": ["2/5", "3/5", "3/7", "4/7"], "c": 1 },
    { "q": "Quy đồng mẫu số 5/8 và 3/4:", "a": ["5/8 và 6/8", "10/16 và 12/16", "15/24 và 16/24", "2/8 và 3/8"], "c": 1 },
    { "q": "Rút gọn phân số 27/36:", "a": ["3/4", "1/2", "2/3", "4/5"], "c": 2 },
    { "q": "So sánh 11/12 và 5/6:", "a": ["11/12 > 5/6", "11/12 < 5/6", "Bằng nhau", "Không so sánh được"], "c": 0 },
    { "q": "Phân số 16/40 rút gọn là:", "a": ["4/10", "2/5", "1/5", "3/8"], "c": 1 },
    { "q": "Chu vi hình chữ nhật có chiều dài 8 cm, chiều rộng 5 cm là:", "a": ["26 cm", "40 cm", "13 cm", "20 cm"], "c": 0 },
    { "q": "Diện tích hình chữ nhật có chiều dài 7 m, chiều rộng 4 m là:", "a": ["11 m²", "28 m²", "14 m²", "21 m²"], "c": 1 },
    { "q": "Chu vi hình vuông có cạnh 9 cm là:", "a": ["18 cm", "36 cm", "27 cm", "81 cm"], "c": 1 },
    { "q": "Diện tích hình vuông cạnh 6 m là:", "a": ["12 m²", "36 m²", "18 m²", "24 m²"], "c": 1 },
    { "q": "Hình chữ nhật có chiều dài 12 cm, chiều rộng 3 cm, chu vi là:", "a": ["15 cm", "30 cm", "30 m", "18 cm"], "c": 1 },
    { "q": "Hình chữ nhật có chiều dài 10 m, chiều rộng 5 m, diện tích là:", "a": ["50 m²", "15 m²", "100 m²", "25 m²"], "c": 0 },
    { "q": "Chu vi hình vuông cạnh 15 cm là:", "a": ["30 cm", "60 cm", "45 cm", "15 cm"], "c": 1 },
    { "q": "Diện tích hình vuông cạnh 8 cm là:", "a": ["16 cm²", "32 cm²", "64 cm²", "48 cm²"], "c": 2 },
    { "q": "Chu vi hình chữ nhật có chiều dài 9 cm, chiều rộng 7 cm là:", "a": ["16 cm", "32 cm", "30 cm", "28 cm"], "c": 2 },
    { "q": "Diện tích hình chữ nhật có chiều dài 5 m, chiều rộng 6 m là:", "a": ["11 m²", "30 m²", "25 m²", "36 m²"], "c": 1 },
    { "q": "Hình vuông có chu vi 40 cm, cạnh của hình vuông là:", "a": ["8 cm", "10 cm", "12 cm", "15 cm"], "c": 1 },
    { "q": "Hình chữ nhật có chu vi 50 cm, chiều dài 15 cm, chiều rộng là:", "a": ["10 cm", "12 cm", "20 cm", "25 cm"], "c": 0 },
    { "q": "Diện tích hình chữ nhật chiều dài 14 cm, chiều rộng 3 cm là:", "a": ["17 cm²", "42 cm²", "21 cm²", "50 cm²"], "c": 1 },
    { "q": "Chu vi hình vuông cạnh 12 m là:", "a": ["48 m", "36 m", "24 m", "60 m"], "c": 0 },
    { "q": "Diện tích hình vuông cạnh 7 cm là:", "a": ["14 cm²", "49 cm²", "21 cm²", "28 cm²"], "c": 1 },
    { "q": "Chu vi hình chữ nhật chiều dài 6 cm, chiều rộng 4 cm là:", "a": ["20 cm", "24 cm", "12 cm", "16 cm"], "c": 0 },
    { "q": "Diện tích hình chữ nhật có chiều dài 9 m, chiều rộng 5 m là:", "a": ["45 m²", "40 m²", "35 m²", "50 m²"], "c": 0 },
    { "q": "Hình vuông có diện tích 64 m², cạnh của nó là:", "a": ["6 m", "8 m", "10 m", "12 m"], "c": 1 },
    { "q": "Hình chữ nhật có diện tích 48 cm², chiều dài 8 cm, chiều rộng là:", "a": ["4 cm", "5 cm", "6 cm", "7 cm"], "c": 2 },
    { "q": "Chu vi hình chữ nhật dài 20 cm, rộng 10 cm là:", "a": ["30 cm", "40 cm", "50 cm", "60 cm"], "c": 1 },
    { "q": "Diện tích hình chữ nhật dài 15 m, rộng 3 m là:", "a": ["45 m²", "40 m²", "50 m²", "48 m²"], "c": 0 },
    { "q": "Chu vi hình vuông có cạnh 5 cm là:", "a": ["15 cm", "20 cm", "25 cm", "10 cm"], "c": 1 },
    { "q": "Diện tích hình vuông cạnh 9 m là:", "a": ["18 m²", "72 m²", "81 m²", "27 m²"], "c": 2 },
    { "q": "Chu vi hình chữ nhật có chiều dài 11 cm, chiều rộng 4 cm là:", "a": ["15 cm", "30 cm", "28 cm", "20 cm"], "c": 2 },
    { "q": "Diện tích hình chữ nhật dài 7 m, rộng 5 m là:", "a": ["35 m²", "30 m²", "25 m²", "40 m²"], "c": 0 },
    { "q": "Hình vuông có diện tích 121 cm², cạnh là:", "a": ["10 cm", "11 cm", "12 cm", "13 cm"], "c": 1 },
    { "q": "Chu vi hình vuông cạnh 14 m là:", "a": ["56 m", "42 m", "28 m", "48 m"], "c": 0 },
    { "q": "Diện tích hình chữ nhật dài 12 cm, rộng 6 cm là:", "a": ["72 cm²", "60 cm²", "66 cm²", "70 cm²"], "c": 0 },
    { "q": "Chu vi hình chữ nhật dài 8 m, rộng 5 m là:", "a": ["26 m", "30 m", "28 m", "32 m"], "c": 2 },
    { "q": "Diện tích hình vuông cạnh 10 cm là:", "a": ["20 cm²", "100 cm²", "50 cm²", "40 cm²"], "c": 1 },
    { "q": "Chu vi hình tam giác có các cạnh 5 cm, 6 cm, 7 cm là:", "a": ["18 cm", "16 cm", "15 cm", "17 cm"], "c": 0 },
    { "q": "Diện tích hình tam giác đáy 6 cm, chiều cao 4 cm là:", "a": ["10 cm²", "12 cm²", "24 cm²", "20 cm²"], "c": 1 },
    { "q": "Chu vi hình tam giác đều cạnh 8 cm là:", "a": ["16 cm", "24 cm", "32 cm", "20 cm"], "c": 1 },
    { "q": "Diện tích hình tam giác vuông đáy 5 cm, chiều cao 12 cm là:", "a": ["30 cm²", "60 cm²", "25 cm²", "17 cm²"], "c": 0 },
    { "q": "Chu vi hình tròn bán kính 7 cm (π ≈ 3,14) là:", "a": ["43,96 cm", "21,98 cm", "49 cm", "14 cm"], "c": 0 },
    { "q": "Diện tích hình tròn bán kính 5 cm (π ≈ 3,14) là:", "a": ["78,5 cm²", "31,4 cm²", "25 cm²", "50 cm²"], "c": 0 },
    { "q": "Chu vi hình tam giác cân đáy 10 cm, hai cạnh bên 7 cm là:", "a": ["24 cm", "14 cm", "20 cm", "27 cm"], "c": 0 },
    { "q": "Diện tích hình chữ nhật dài 18 cm, rộng 7 cm là:", "a": ["125 cm²", "126 cm²", "124 cm²", "130 cm²"], "c": 1 },
    { "q": "Chu vi hình vuông cạnh 13 cm là:", "a": ["52 cm", "26 cm", "39 cm", "65 cm"], "c": 0 },
    { "q": "Diện tích hình vuông cạnh 14 m là:", "a": ["196 m²", "56 m²", "28 m²", "42 m²"], "c": 0 },
    { "q": "Chu vi hình chữ nhật dài 15 cm, rộng 9 cm là:", "a": ["48 cm", "36 cm", "30 cm", "50 cm"], "c": 0 },
    { "q": "Diện tích hình chữ nhật dài 20 cm, rộng 5 cm là:", "a": ["100 cm²", "105 cm²", "95 cm²", "90 cm²"], "c": 0 },
    { "q": "Chu vi hình tam giác có các cạnh 3 cm, 4 cm, 5 cm là:", "a": ["12 cm", "10 cm", "15 cm", "14 cm"], "c": 0 },
    { "q": "Diện tích hình tam giác vuông đáy 8 cm, chiều cao 6 cm là:", "a": ["24 cm²", "48 cm²", "14 cm²", "28 cm²"], "c": 0 },
    { "q": "Chu vi hình tròn bán kính 10 cm (π ≈ 3,14) là:", "a": ["62,8 cm", "31,4 cm", "50 cm", "20 cm"], "c": 0 },
    { "q": "Diện tích hình tròn bán kính 7 cm (π ≈ 3,14) là:", "a": ["153,86 cm²", "49 cm²", "43,96 cm²", "100 cm²"], "c": 0 },
    { "q": "Chu vi hình tam giác đều cạnh 6 cm là:", "a": ["18 cm", "12 cm", "24 cm", "15 cm"], "c": 0 },
    { "q": "Diện tích hình tam giác đáy 9 cm, chiều cao 8 cm là:", "a": ["36 cm²", "72 cm²", "32 cm²", "40 cm²"], "c": 0 },
    { "q": "Chu vi hình chữ nhật dài 11 m, rộng 4 m là:", "a": ["30 m", "28 m", "24 m", "32 m"], "c": 0 },
    { "q": "Diện tích hình chữ nhật dài 13 cm, rộng 6 cm là:", "a": ["78 cm²", "76 cm²", "72 cm²", "80 cm²"], "c": 0 },
    { "q": "Chu vi hình vuông cạnh 16 cm là:", "a": ["64 cm", "32 cm", "48 cm", "60 cm"], "c": 0 },
    { "q": "Diện tích hình vuông cạnh 18 m là:", "a": ["324 m²", "36 m²", "72 m²", "108 m²"], "c": 0 },
    { "q": "Chu vi hình chữ nhật dài 14 cm, rộng 9 cm là:", "a": ["46 cm", "40 cm", "42 cm", "48 cm"], "c": 2 },
    { "q": "Diện tích hình chữ nhật dài 17 cm, rộng 5 cm là:", "a": ["85 cm²", "80 cm²", "75 cm²", "90 cm²"], "c": 0 },
    { "q": "Chu vi hình tam giác cân đáy 12 cm, hai cạnh bên 10 cm là:", "a": ["32 cm", "34 cm", "30 cm", "36 cm"], "c": 0 },
    { "q": "Diện tích hình tam giác vuông đáy 10 cm, chiều cao 6 cm là:", "a": ["30 cm²", "60 cm²", "50 cm²", "40 cm²"], "c": 0 },
    { "q": "Chu vi hình tròn bán kính 5 cm (π ≈ 3,14) là:", "a": ["31,4 cm", "15,7 cm", "25 cm", "10 cm"], "c": 0 },
    { "q": "Diện tích hình tròn bán kính 10 cm (π ≈ 3,14) là:", "a": ["314 cm²", "100 cm²", "62,8 cm²", "50 cm²"], "c": 0 },
    { "q": "Chu vi hình tam giác có các cạnh 7 cm, 9 cm, 10 cm là:", "a": ["26 cm", "25 cm", "24 cm", "27 cm"], "c": 0 },
    { "q": "Diện tích hình tam giác đáy 12 cm, chiều cao 5 cm là:", "a": ["30 cm²", "60 cm²", "50 cm²", "40 cm²"], "c": 0 },
    { "q": "1 m = ? cm", "a": ["10 cm", "100 cm", "1000 cm", "1 cm"], "c": 1 },
    { "q": "1 km = ? m", "a": ["100 m", "1000 m", "10 m", "10000 m"], "c": 1 },
    { "q": "1 dm = ? mm", "a": ["10 mm", "100 mm", "1000 mm", "1 mm"], "c": 1 },
    { "q": "1 m² = ? cm²", "a": ["100 cm²", "1000 cm²", "10000 cm²", "100000 cm²"], "c": 2 },
    { "q": "1 km² = ? m²", "a": ["10000 m²", "100000 m²", "1000000 m²", "1000 m²"], "c": 2 },
    { "q": "1 l = ? ml", "a": ["10 ml", "100 ml", "1000 ml", "10000 ml"], "c": 2 },
    { "q": "1 kg = ? g", "a": ["100 g", "1000 g", "10 g", "10000 g"], "c": 1 },
    { "q": "1 tấn = ? kg", "a": ["100 kg", "1000 kg", "10000 kg", "10 kg"], "c": 1 },
    { "q": "1 h = ? phút", "a": ["60 phút", "100 phút", "1000 phút", "120 phút"], "c": 0 },
    { "q": "1 phút = ? giây", "a": ["30 giây", "60 giây", "100 giây", "120 giây"], "c": 1 },
    { "q": "5 km = ? m", "a": ["500 m", "5000 m", "50 m", "50 km"], "c": 1 },
    { "q": "3 m² = ? cm²", "a": ["300 cm²", "3000 cm²", "30000 cm²", "300000 cm²"], "c": 2 },
    { "q": "7 l = ? ml", "a": ["700 ml", "7000 ml", "70 ml", "70000 ml"], "c": 1 },
    { "q": "2 kg = ? g", "a": ["200 g", "2000 g", "20 g", "20000 g"], "c": 1 },
    { "q": "0,5 tấn = ? kg", "a": ["50 kg", "500 kg", "5 kg", "5000 kg"], "c": 1 },
    { "q": "90 phút = ? h", "a": ["1 h 30 phút", "2 h", "1 h", "1 h 15 phút"], "c": 0 },
    { "q": "3600 giây = ? h", "a": ["1 h", "2 h", "60 h", "0,5 h"], "c": 0 },
    { "q": "2500 ml = ? l", "a": ["2,5 l", "25 l", "0,25 l", "0,025 l"], "c": 0 },
    { "q": "120 cm = ? m", "a": ["1,2 m", "12 m", "0,12 m", "0,012 m"], "c": 0 },
    { "q": "15 km² = ? m²", "a": ["1500 m²", "15000 m²", "150000 m²", "15000000 m²"], "c": 3 },
    { "q": "0,75 kg = ? g", "a": ["7,5 g", "75 g", "750 g", "0,75 g"], "c": 2 },
    { "q": "2000 ml = ? l", "a": ["2 l", "20 l", "0,2 l", "200 l"], "c": 0 },
    { "q": "0,5 m² = ? cm²", "a": ["50 cm²", "500 cm²", "5000 cm²", "50000 cm²"], "c": 3 },
    { "q": "4 h = ? phút", "a": ["240 phút", "400 phút", "60 phút", "120 phút"], "c": 0 },
    { "q": "360 phút = ? h", "a": ["3 h", "6 h", "5 h", "4 h"], "c": 1 },
    { "q": "0,25 tấn = ? kg", "a": ["25 kg", "250 kg", "2,5 kg", "0,25 kg"], "c": 1 },
    { "q": "1,5 km = ? m", "a": ["150 m", "1500 m", "15 m", "15000 m"], "c": 1 },
    { "q": "0,02 m² = ? cm²", "a": ["2 cm²", "20 cm²", "200 cm²", "2000 cm²"], "c": 2 },
    { "q": "3 h 30 phút = ? phút", "a": ["210 phút", "200 phút", "180 phút", "230 phút"], "c": 0 },
    { "q": "2,5 l = ? ml", "a": ["250 ml", "2500 ml", "25 ml", "2000 ml"], "c": 1 },
    { "q": "5,5 km = ? m", "a": ["550 m", "5500 m", "500 m", "5050 m"], "c": 1 },
    { "q": "12,7 m = ? cm", "a": ["127 cm", "1270 cm", "12,7 cm", "1207 cm"], "c": 1 },
    { "q": "0,8 tấn = ? kg", "a": ["8 kg", "80 kg", "800 kg", "8000 kg"], "c": 2 },
    { "q": "3,25 l = ? ml", "a": ["325 ml", "3250 ml", "32,5 ml", "3000 ml"], "c": 1 },
    { "q": "7,5 h = ? phút", "a": ["450 phút", "75 phút", "7,5 phút", "700 phút"], "c": 0 },
    { "q": "3600 s = ? h", "a": ["0,5 h", "1 h", "10 h", "6 h"], "c": 1 },
    { "q": "0,03 km² = ? m²", "a": ["300 m²", "3000 m²", "30000 m²", "300000 m²"], "c": 2 },
    { "q": "0,004 m² = ? cm²", "a": ["0,4 cm²", "4 cm²", "40 cm²", "400 cm²"], "c": 3 },
    { "q": "2,75 m² = ? cm²", "a": ["275 cm²", "2750 cm²", "27500 cm²", "275000 cm²"], "c": 2 },
    { "q": "1,2 tấn = ? kg", "a": ["120 kg", "1200 kg", "12 kg", "1,2 kg"], "c": 1 },
    { "q": "4500 ml = ? l", "a": ["4,5 l", "45 l", "0,45 l", "450 l"], "c": 0 },
    { "q": "0,125 km = ? m", "a": ["1250 m", "125 m", "12,5 m", "1,25 m"], "c": 1 },
    { "q": "0,06 tấn = ? kg", "a": ["6 kg", "60 kg", "600 kg", "0,6 kg"], "c": 1 },
    { "q": "0,75 h = ? phút", "a": ["45 phút", "75 phút", "7,5 phút", "30 phút"], "c": 0 },
    { "q": "180 phút = ? h", "a": ["2 h", "3 h", "1 h", "1,5 h"], "c": 1 },
    { "q": "0,025 m² = ? cm²", "a": ["2,5 cm²", "25 cm²", "250 cm²", "2500 cm²"], "c": 2 },
    { "q": "5,4 l = ? ml", "a": ["54 ml", "540 ml", "5400 ml", "5,4 ml"], "c": 2 },
    { "q": "0,9 km = ? m", "a": ["90 m", "900 m", "9000 m", "9 m"], "c": 1 },
    { "q": "0,5 m² = ? cm²", "a": ["50 cm²", "500 cm²", "5000 cm²", "50000 cm²"], "c": 3 },
    { "q": "0,2 tấn = ? kg", "a": ["20 kg", "200 kg", "2 kg", "2000 kg"], "c": 1 },
    { "q": "0,65 h = ? phút", "a": ["39 phút", "65 phút", "35 phút", "45 phút"], "c": 0 },
    { "q": "7,5 l = ? ml", "a": ["75 ml", "750 ml", "7500 ml", "7,5 ml"], "c": 2 },
    { "q": "0,003 km² = ? m²", "a": ["30 m²", "300 m²", "3000 m²", "30000 m²"], "c": 3 },
    { "q": "0,2 m² = ? cm²", "a": ["20 cm²", "200 cm²", "2000 cm²", "20000 cm²"], "c": 3 },
    { "q": "0,015 tấn = ? kg", "a": ["1,5 kg", "15 kg", "150 kg", "0,15 kg"], "c": 1 },
    { "q": "2,5 h = ? phút", "a": ["125 phút", "150 phút", "250 phút", "200 phút"], "c": 1 },
    { "q": "3,6 km = ? m", "a": ["36 m", "360 m", "3600 m", "3,6 m"], "c": 2 },
    { "q": "0,08 m² = ? cm²", "a": ["8 cm²", "80 cm²", "800 cm²", "8000 cm²"], "c": 2 },
    { "q": "1250 ml = ? l", "a": ["1,25 l", "12,5 l", "0,125 l", "125 l"], "c": 0 },
    { "q": "0,45 tấn = ? kg", "a": ["4,5 kg", "45 kg", "450 kg", "0,45 kg"], "c": 2 },
    { "q": "3,5 km² = ? m²", "a": ["35000 m²", "350000 m²", "3500000 m²", "35000000 m²"], "c": 2 },
    { "q": "4,75 h = ? phút", "a": ["285 phút", "275 phút", "245 phút", "250 phút"], "c": 0 },
    { "q": "0,125 tấn = ? kg", "a": ["12,5 kg", "125 kg", "1,25 kg", "0,125 kg"], "c": 1 },
    { "q": "2,4 m³ = ? l", "a": ["240 l", "2400 l", "2,4 l", "24 l"], "c": 1 },
    { "q": "0,06 km = ? m", "a": ["0,6 m", "6 m", "60 m", "600 m"], "c": 2 },
    { "q": "0,008 km² = ? m²", "a": ["8 m²", "80 m²", "800 m²", "8000 m²"], "c": 3 },
    { "q": "7,5 h = ? phút", "a": ["450 phút", "400 phút", "475 phút", "425 phút"], "c": 0 },
    { "q": "0,375 tấn = ? kg", "a": ["37,5 kg", "375 kg", "3,75 kg", "0,375 kg"], "c": 1 },
    { "q": "1,25 m² = ? cm²", "a": ["125 cm²", "1250 cm²", "12500 cm²", "125000 cm²"], "c": 2 },
    { "q": "0,02 m³ = ? l", "a": ["2 l", "20 l", "200 l", "2000 l"], "c": 1 },
    { "q": "0,045 km² = ? m²", "a": ["450 m²", "4500 m²", "45000 m²", "450000 m²"], "c": 3 },
    { "q": "5,25 h = ? phút", "a": ["315 phút", "325 phút", "305 phút", "300 phút"], "c": 0 },
    { "q": "0,18 tấn = ? kg", "a": ["18 kg", "180 kg", "1,8 kg", "0,18 kg"], "c": 1 },
    { "q": "2,75 m³ = ? l", "a": ["275 l", "2750 l", "27,5 l", "2500 l"], "c": 1 },
    { "q": "0,65 km = ? m", "a": ["65 m", "650 m", "6,5 m", "0,65 m"], "c": 1 },
    { "q": "0,09 m² = ? cm²", "a": ["9 cm²", "90 cm²", "900 cm²", "9000 cm²"], "c": 2 },
    { "q": "1,5 tấn = ? kg", "a": ["150 kg", "1500 kg", "15 kg", "1,5 kg"], "c": 1 },
    { "q": "3,6 h = ? phút", "a": ["216 phút", "360 phút", "36 phút", "180 phút"], "c": 0 },
    { "q": "0,07 km² = ? m²", "a": ["700 m²", "7000 m²", "70000 m²", "700000 m²"], "c": 3 },
    { "q": "0,32 m³ = ? l", "a": ["32 l", "320 l", "3,2 l", "300 l"], "c": 1 },
    { "q": "0,055 tấn = ? kg", "a": ["5,5 kg", "55 kg", "0,55 kg", "500 kg"], "c": 1 },
    { "q": "2,8 km = ? m", "a": ["280 m", "2800 m", "28 m", "2,8 m"], "c": 1 },
    { "q": "0,005 km² = ? m²", "a": ["50 m²", "500 m²", "5000 m²", "50000 m²"], "c": 2 },
    { "q": "6,25 h = ? phút", "a": ["375 phút", "625 phút", "325 phút", "350 phút"], "c": 0 },
    { "q": "0,22 tấn = ? kg", "a": ["2,2 kg", "22 kg", "220 kg", "0,22 kg"], "c": 2 },
    { "q": "1,85 m³ = ? l", "a": ["185 l", "1850 l", "18,5 l", "1800 l"], "c": 1 },
    { "q": "0,09 km = ? m", "a": ["9 m", "90 m", "900 m", "9000 m"], "c": 2 },
    { "q": "0,12 m² = ? cm²", "a": ["12 cm²", "120 cm²", "1200 cm²", "12000 cm²"], "c": 3 },
    { "q": "4,6 h = ? phút", "a": ["276 phút", "260 phút", "246 phút", "286 phút"], "c": 0 },
    { "q": "0,38 tấn = ? kg", "a": ["3,8 kg", "38 kg", "380 kg", "0,38 kg"], "c": 2 },
    { "q": "Từ nào sau đây là danh từ?", "a": ["Chạy", "Đẹp", "Trường", "Nhanh"], "c": 2 },
    { "q": "Từ nào là động từ?", "a": ["Cô giáo", "Chơi", "Xinh đẹp", "Bút"], "c": 1 },
    { "q": "Từ nào là tính từ?", "a": ["Đẹp", "Đọc", "Học sinh", "Bàn"], "c": 0 },
    { "q": "Chọn từ là danh từ:", "a": ["Chạy", "Ngôi nhà", "Nhanh", "Nhảy"], "c": 1 },
    { "q": "Chọn từ là động từ:", "a": ["Hoa", "Chạy", "Xinh đẹp", "Sách"], "c": 1 },
    { "q": "Chọn từ là tính từ:", "a": ["Vui vẻ", "Cô giáo", "Đọc sách", "Bút chì"], "c": 0 },
    { "q": "Từ nào sau đây là danh từ?", "a": ["Quyển sách", "Chơi bóng", "Tốt", "Nhanh chóng"], "c": 0 },
    { "q": "Từ nào là động từ?", "a": ["Học sinh", "Ngủ", "Đẹp", "Hoa"], "c": 1 },
    { "q": "Từ nào là tính từ?", "a": ["Cao", "Chạy nhanh", "Trường học", "Bút bi"], "c": 0 },
    { "q": "Chọn từ là danh từ:", "a": ["Mèo", "Chạy", "Nhanh", "Vui"], "c": 0 },
    { "q": "Chọn từ là động từ:", "a": ["Ăn", "Hoa hồng", "Xinh xắn", "Cái bàn"], "c": 0 },
    { "q": "Chọn từ là tính từ:", "a": ["Thông minh", "Học sinh", "Chơi đùa", "Sách vở"], "c": 0 },
    { "q": "Từ nào là danh từ?", "a": ["Trái táo", "Chạy nhảy", "Đẹp", "Nhanh nhẹn"], "c": 0 },
    { "q": "Từ nào là động từ?", "a": ["Người bạn", "Viết", "Đẹp trai", "Cái ghế"], "c": 1 },
    { "q": "Từ nào là tính từ?", "a": ["Dễ thương", "Đi học", "Cô giáo", "Quyển vở"], "c": 0 },
    { "q": "Chọn từ là danh từ:", "a": ["Cây xanh", "Chạy bộ", "Nhanh nhẹn", "Vui vẻ"], "c": 0 },
    { "q": "Chọn từ là động từ:", "a": ["Hát", "Hoa sen", "Xinh đẹp", "Quyển sách"], "c": 0 },
    { "q": "Chọn từ là tính từ:", "a": ["Cao lớn", "Chơi cờ", "Người bạn", "Bút chì"], "c": 0 },
    { "q": "Từ nào là danh từ?", "a": ["Bệnh viện", "Chạy nhảy", "Đẹp", "Nhanh"], "c": 0 },
    { "q": "Từ nào là động từ?", "a": ["Ngủ trưa", "Ngôi nhà", "Xinh đẹp", "Quyển sách"], "c": 0 },
    { "q": "Từ nào là tính từ?", "a": ["Vui vẻ", "Đọc sách", "Cây cối", "Bút bi"], "c": 0 },
    { "q": "Chọn từ là danh từ:", "a": ["Máy tính", "Chạy nhanh", "Đẹp trai", "Vui"], "c": 0 },
    { "q": "Chọn từ là động từ:", "a": ["Chơi bóng", "Cái bàn", "Thông minh", "Hoa hồng"], "c": 0 },
    { "q": "Chọn từ là tính từ:", "a": ["Nhỏ bé", "Học bài", "Người bạn", "Quyển vở"], "c": 0 },
    { "q": "Từ nào là danh từ?", "a": ["Trường học", "Chạy nhảy", "Xinh đẹp", "Nhanh nhẹn"], "c": 0 },
    { "q": "Từ nào là động từ?", "a": ["Đi bộ", "Bút bi", "Đẹp trai", "Cây cối"], "c": 0 },
    { "q": "Từ nào là tính từ?", "a": ["Dễ thương", "Ngủ trưa", "Hoa hồng", "Quyển sách"], "c": 0 },
    { "q": "Chọn từ là danh từ:", "a": ["Xe đạp", "Chạy bộ", "Vui vẻ", "Cao lớn"], "c": 0 },
    { "q": "Chọn từ là động từ:", "a": ["Ăn cơm", "Cái ghế", "Xinh đẹp", "Người bạn"], "c": 0 },
    { "q": "Chọn từ là tính từ:", "a": ["Thân thiện", "Học sinh", "Chơi đùa", "Bút chì"], "c": 0 },
    { "q": "Từ nào là danh từ trong câu: 'Cô giáo dạy chúng em bài toán mới.'?", "a": ["Cô giáo", "dạy", "mới", "chúng em"], "c": 0 },
    { "q": "Từ nào là động từ trong câu: 'Bé Minh đang chạy trong sân trường.'?", "a": ["Bé Minh", "chạy", "trong", "sân trường"], "c": 1 },
    { "q": "Từ nào là tính từ trong câu: 'Cô gái xinh đẹp đang đọc sách.'?", "a": ["Cô gái", "xinh đẹp", "đọc", "sách"], "c": 1 },
    { "q": "Từ nào là danh từ trong câu: 'Quyển sách này rất thú vị.'?", "a": ["Quyển sách", "rất", "thú vị", "này"], "c": 0 },
    { "q": "Từ nào là động từ trong câu: 'Chúng tôi học bài chăm chỉ mỗi ngày.'?", "a": ["Chúng tôi", "học", "bài", "mỗi ngày"], "c": 1 },
    { "q": "Từ nào là tính từ trong câu: 'Ngôi nhà cao và rộng.'?", "a": ["Ngôi nhà", "cao", "rộng", "và"], "c": 1 },
    { "q": "Từ nào là danh từ trong câu: 'Hoa hồng đỏ tỏa hương thơm.'?", "a": ["Hoa hồng", "đỏ", "tỏa", "thơm"], "c": 0 },
    { "q": "Từ nào là động từ trong câu: 'Bố đang sửa xe trong garage.'?", "a": ["Bố", "sửa", "xe", "garage"], "c": 1 },
    { "q": "Từ nào là tính từ trong câu: 'Chiếc áo mới rất đẹp.'?", "a": ["Chiếc áo", "mới", "rất", "đẹp"], "c": 1 },
    { "q": "Từ nào là danh từ trong câu: 'Con mèo đang ngủ trên ghế.'?", "a": ["Con mèo", "ngủ", "trên", "ghế"], "c": 0 },
    { "q": "Từ nào là động từ trong câu: 'Em bé cười rất tươi.'?", "a": ["Em bé", "cười", "rất", "tươi"], "c": 1 },
    { "q": "Từ nào là tính từ trong câu: 'Bức tranh này thật sống động.'?", "a": ["Bức tranh", "này", "sống động", "thật"], "c": 2 },
    { "q": "Từ nào là danh từ trong câu: 'Người bạn tốt luôn giúp đỡ mọi người.'?", "a": ["Người bạn", "tốt", "giúp đỡ", "mọi người"], "c": 0 },
    { "q": "Từ nào là động từ trong câu: 'Chúng tôi cùng nhau làm bài tập.'?", "a": ["Chúng tôi", "làm", "bài tập", "cùng nhau"], "c": 1 },
    { "q": "Từ nào là tính từ trong câu: 'Cây cao nhất trong vườn.'?", "a": ["Cây", "cao", "trong", "vườn"], "c": 1 },
    { "q": "Từ nào là danh từ trong câu: 'Con sông dài chảy qua thành phố.'?", "a": ["Con sông", "dài", "chảy", "thành phố"], "c": 0 },
    { "q": "Từ nào là động từ trong câu: 'Bố nấu cơm rất ngon.'?", "a": ["Bố", "nấu", "cơm", "ngon"], "c": 1 },
    { "q": "Từ nào là tính từ trong câu: 'Chú chó mập đang chơi ngoài sân.'?", "a": ["Chú chó", "mập", "chơi", "ngoài sân"], "c": 1 },
    { "q": "Từ nào là danh từ trong câu: 'Quán cà phê mới mở gần nhà tôi.'?", "a": ["Quán cà phê", "mới", "gần", "nhà"], "c": 0 },
    { "q": "Từ nào là động từ trong câu: 'Chị Lan vẽ bức tranh thật đẹp.'?", "a": ["Chị Lan", "vẽ", "bức tranh", "đẹp"], "c": 1 },
    { "q": "Từ nào là tính từ trong câu: 'Chiếc xe hơi màu đỏ rất sang trọng.'?", "a": ["Chiếc xe hơi", "màu đỏ", "sang trọng", "rất"], "c": 2 },
    { "q": "Từ nào là danh từ trong câu: 'Ngôi trường của chúng tôi nằm ở ngoại ô.'?", "a": ["Ngôi trường", "chúng tôi", "nằm", "ngoại ô"], "c": 0 },
    { "q": "Từ nào là động từ trong câu: 'Các bạn nhỏ nhảy múa trên sân khấu.'?", "a": ["Các bạn nhỏ", "nhảy múa", "sân khấu", "trên"], "c": 1 },
    { "q": "Từ nào là tính từ trong câu: 'Cháu bé thông minh học rất giỏi.'?", "a": ["Cháu bé", "thông minh", "học", "rất"], "c": 1 },
    { "q": "Từ nào là danh từ trong câu: 'Cây bàng trước sân trường cao lớn.'?", "a": ["Cây bàng", "trước sân trường", "cao lớn", "trường"], "c": 0 },
    { "q": "Từ nào là động từ trong câu: 'Bố mẹ chăm sóc cây cối trong vườn.'?", "a": ["Bố mẹ", "chăm sóc", "cây cối", "vườn"], "c": 1 },
    { "q": "Từ nào là tính từ trong câu: 'Con mèo trắng rất hiền lành.'?", "a": ["Con mèo", "trắng", "rất", "hiền lành"], "c": 1 },
    { "q": "Từ nào là danh từ trong câu: 'Buổi chiều nắng đẹp trên bãi biển.'?", "a": ["Buổi chiều", "nắng", "bãi biển", "đẹp"], "c": 0 },
    { "q": "Từ nào là động từ trong câu: 'Chị ấy lau bàn thật sạch sẽ.'?", "a": ["Chị ấy", "lau", "bàn", "sạch sẽ"], "c": 1 },
    { "q": "Từ nào là tính từ trong câu: 'Trái cây tươi ngon trên kệ.'?", "a": ["Trái cây", "tươi ngon", "kệ", "trên"], "c": 1 },
    { "q": "Câu nào sau đây là câu kể?", "a": ["Trời hôm nay nắng đẹp.", "Bạn có khỏe không?", "Hãy đóng cửa lại.", "Thật là tuyệt vời!"], "c": 0 },
    { "q": "Câu nào là câu hỏi?", "a": ["Mẹ đang nấu cơm.", "Bạn học bài chưa?", "Đừng chạy quá nhanh!", "Ôi! Mình vui quá!"], "c": 1 },
    { "q": "Câu nào là câu khiến?", "a": ["Hãy đọc sách đi.", "Trời mưa rồi.", "Bạn có thích món này không?", "Thật là vui!"], "c": 0 },
    { "q": "Câu nào là câu cảm?", "a": ["Tôi đã hoàn thành bài tập.", "Bạn đang làm gì vậy?", "Ôi! Thật là đẹp!", "Hãy giúp tôi với!"], "c": 2 },
    { "q": "Câu nào là câu kể?", "a": ["Cô giáo dạy chúng em bài mới.", "Bạn có muốn đi chơi không?", "Hãy mở cửa sổ.", "Thật là bất ngờ!"], "c": 0 },
    { "q": "Câu nào là câu hỏi?", "a": ["Chúng tôi đi học vào buổi sáng.", "Em đã ăn chưa?", "Xin vui lòng đợi tôi một chút.", "Ôi! Mình mệt quá!"], "c": 1 },
    { "q": "Câu nào là câu khiến?", "a": ["Hãy viết tên bạn vào vở.", "Trời hôm nay mưa.", "Bạn có biết câu trả lời không?", "Thật là đáng yêu!"], "c": 0 },
    { "q": "Câu nào là câu cảm?", "a": ["Tôi thích đọc sách.", "Bạn có đi đâu không?", "Ôi! Món ăn này ngon quá!", "Hãy đến đây ngay!"], "c": 2 },
    { "q": "Câu nào là câu kể?", "a": ["Chú mèo đang ngủ trên ghế.", "Bạn có muốn uống nước không?", "Đừng làm ồn!", "Ôi! Cái cây cao quá!"], "c": 0 },
    { "q": "Câu nào là câu hỏi?", "a": ["Bài học hôm nay khó quá.", "Em đã làm xong chưa?", "Hãy lấy bút cho tôi.", "Ôi! Thật là tuyệt vời!"], "c": 1 },
    { "q": "Câu nào là câu khiến?", "a": ["Hãy giữ im lặng.", "Chúng tôi đi dạo công viên.", "Bạn có thích bài hát này không?", "Ôi! Mình vui quá!"], "c": 0 },
    { "q": "Câu nào là câu cảm?", "a": ["Cô giáo dạy rất nhiệt tình.", "Bạn có biết đường đến nhà tôi không?", "Ôi! Trời mưa rồi!", "Hãy xem giúp tôi!"], "c": 2 },
    { "q": "Câu nào là câu kể?", "a": ["Bố đang làm vườn.", "Bạn đã ăn chưa?", "Hãy cẩn thận khi đi qua đường.", "Ôi! Mình hạnh phúc quá!"], "c": 0 },
    { "q": "Câu nào là câu hỏi?", "a": ["Mẹ đang nấu ăn.", "Em có muốn đi học không?", "Hãy mở sách ra.", "Ôi! Cái bánh này ngon quá!"], "c": 1 },
    { "q": "Câu nào là câu khiến?", "a": ["Hãy rửa tay trước khi ăn.", "Trời đang nắng.", "Bạn có biết hôm nay là thứ mấy không?", "Ôi! Thật là tuyệt vời!"], "c": 0 },
    { "q": "Câu nào là câu cảm?", "a": ["Tôi đi học đều đặn mỗi ngày.", "Bạn có muốn đi chơi không?", "Thật là vui quá!", "Hãy làm bài tập đầy đủ."], "c": 2 },
    { "q": "Câu nào là câu kể?", "a": ["Chúng tôi đi thăm ông bà vào cuối tuần.", "Bạn có muốn đi cùng không?", "Hãy ngồi xuống.", "Ôi! Mình thích quá!"], "c": 0 },
    { "q": "Câu nào là câu hỏi?", "a": ["Trời hôm nay lạnh quá.", "Bạn đã làm bài tập chưa?", "Hãy đọc sách đi.", "Ôi! Cái bánh này ngon quá!"], "c": 1 },
    { "q": "Câu nào là câu khiến?", "a": ["Hãy đóng cửa sổ lại.", "Chúng tôi đang đi học.", "Bạn có muốn ăn không?", "Ôi! Thật là đẹp!"], "c": 0 },
    { "q": "Câu nào là câu cảm?", "a": ["Mẹ đang nấu cơm.", "Bạn có biết đường không?", "Ôi! Trời đẹp quá!", "Hãy giúp tôi một việc."], "c": 2 },
    { "q": "Câu nào là câu kể?", "a": ["Bài hát này rất hay.", "Bạn có đi học hôm nay không?", "Hãy giữ im lặng.", "Ôi! Thật là tuyệt vời!"], "c": 0 },
    { "q": "Câu nào là câu hỏi?", "a": ["Em đang chơi với bạn.", "Bạn đã ăn sáng chưa?", "Hãy viết tên bạn vào vở.", "Ôi! Mình vui quá!"], "c": 1 },
    { "q": "Câu nào là câu khiến?", "a": ["Hãy uống nước đầy đủ.", "Chúng tôi đang học bài.", "Bạn có biết câu trả lời không?", "Ôi! Món ăn này ngon quá!"], "c": 0 },
    { "q": "Câu nào là câu cảm?", "a": ["Cây cối xanh tươi.", "Bạn có thích món này không?", "Ôi! Mình thích bài hát này quá!", "Hãy làm bài tập đầy đủ."], "c": 2 },
    { "q": "Câu nào là câu kể?", "a": ["Ngôi nhà của tôi rất rộng.", "Bạn có đi chơi hôm nay không?", "Hãy cẩn thận khi đi đường.", "Ôi! Thật là tuyệt vời!"], "c": 0 },
    { "q": "Câu nào là câu hỏi?", "a": ["Trời mưa rồi.", "Em có muốn ăn kem không?", "Hãy ngồi xuống.", "Ôi! Mình vui quá!"], "c": 1 },
    { "q": "Câu nào là câu khiến?", "a": ["Hãy mở cửa sổ.", "Chúng tôi đi học muộn hôm nay.", "Bạn có biết đường về nhà không?", "Ôi! Thật là đẹp!"], "c": 0 },
    { "q": "Câu nào là câu cảm?", "a": ["Bài tập hôm nay khá dễ.", "Bạn có muốn đi chơi không?", "Ôi! Trời nắng quá!", "Hãy làm bài tập cẩn thận."], "c": 2 },
    { "q": "Câu nào là câu kể?", "a": ["Chú chó đang ngủ dưới gốc cây.", "Bạn có đi cùng chúng tôi không?", "Hãy đứng lên.", "Ôi! Mình thích quá!"], "c": 0 },
    { "q": "Câu nào là câu hỏi?", "a": ["Mẹ đang nấu ăn.", "Bạn đã đọc sách hôm nay chưa?", "Hãy giúp tôi một việc.", "Ôi! Trời đẹp quá!"], "c": 1 },
    { "q": "Câu nào là câu khiến?", "a": ["Hãy viết tên bạn lên bảng.", "Chúng tôi đi dạo công viên.", "Bạn có biết bài học chưa?", "Ôi! Thật là vui!"], "c": 0 },
    { "q": "Câu nào là câu cảm?", "a": ["Ngôi trường của chúng tôi rộng rãi.", "Bạn có muốn đi đâu không?", "Ôi! Mình thích món ăn này quá!", "Hãy làm bài tập đầy đủ."], "c": 2 },
    { "q": "Câu nào sau đây có sử dụng biện pháp nhân hóa?", "a": ["Gió hát ru những cánh đồng.", "Mặt trời to như quả cầu lửa.", "Cô giáo dạy bài mới.", "Bạn có khỏe không?"], "c": 0 },
    { "q": "Câu nào sau đây có sử dụng biện pháp so sánh?", "a": ["Mắt em sáng như ngọc.", "Cây đứng hiên ngang giữa sân.", "Bầu trời trong xanh.", "Chúng tôi đi học đều đặn."], "c": 0 },
    { "q": "Câu nào sử dụng nhân hóa?", "a": ["Con sông cười vui sau cơn mưa.", "Ngôi nhà cao lớn.", "Bạn học bài chăm chỉ.", "Trời hôm nay nắng đẹp."], "c": 0 },
    { "q": "Câu nào sử dụng so sánh?", "a": ["Cháu bé nhanh như gió.", "Bài học hôm nay thú vị.", "Hoa hồng nở rộ trong vườn.", "Chúng tôi cùng nhau chơi bóng."], "c": 0 },
    { "q": "Chọn câu có nhân hóa:", "a": ["Cây cối vẫy tay chào chúng tôi.", "Chiếc xe chạy nhanh trên đường.", "Bạn có biết câu trả lời không?", "Ngôi trường rộng lớn."], "c": 0 },
    { "q": "Chọn câu có so sánh:", "a": ["Mặt trăng sáng như bạc.", "Bố đang làm việc trong vườn.", "Em bé cười vui vẻ.", "Trời hôm nay mưa to."], "c": 0 },
    { "q": "Câu nào có nhân hóa?", "a": ["Đêm đen buông xuống, phố phường chìm vào giấc ngủ.", "Bạn học bài chăm chỉ.", "Cháu bé đang chơi ngoài sân.", "Quyển sách này hay quá."], "c": 0 },
    { "q": "Câu nào có so sánh?", "a": ["Mắt cô ấy sáng như sao.", "Chúng tôi đi dạo công viên.", "Hoa nở rộ trên cành.", "Bài học hôm nay khó quá."], "c": 0 },
    { "q": "Câu nào sử dụng nhân hóa?", "a": ["Cơn gió chạy khắp sân chơi.", "Bức tranh đẹp quá.", "Bạn có làm bài chưa?", "Trời hôm nay nắng nóng."], "c": 0 },
    { "q": "Câu nào sử dụng so sánh?", "a": ["Cháu bé bé nhỏ như con thỏ.", "Ngôi nhà cao ráo.", "Cô giáo dạy bài mới.", "Mặt trời ló rạng."], "c": 0 },
    { "q": "Chọn câu nhân hóa:", "a": ["Mưa rơi tí tách trên mái nhà.", "Bạn học bài chăm chỉ.", "Ngôi trường rộng lớn.", "Ông mặt trời đang tỏa nắng."], "c": 3 },
    { "q": "Chọn câu so sánh:", "a": ["Trái táo đỏ như quả chín mọng.", "Con mèo đang ngủ.", "Cây cao đứng giữa sân.", "Hoa nở rộ trong vườn."], "c": 0 },
    { "q": "Câu nào là nhân hóa?", "a": ["Ngọn lửa nhảy múa trong bếp.", "Trời mưa to.", "Bạn đang đọc sách.", "Chiếc bàn gỗ cũ."], "c": 0 },
    { "q": "Câu nào là so sánh?", "a": ["Tóc em dài như suối.", "Con mèo ngủ trên ghế.", "Quyển sách để trên bàn.", "Cây đứng giữa sân."], "c": 0 },
    { "q": "Câu nào có nhân hóa?", "a": ["Mặt trời cười chào chúng tôi.", "Ngôi nhà cao rộng.", "Bạn học bài chăm chỉ.", "Chiếc xe chạy trên đường."], "c": 0 },
    { "q": "Câu nào có so sánh?", "a": ["Cháu bé chạy nhanh như gió.", "Cây xanh trong vườn.", "Hoa nở rộ trên cành.", "Trời mưa to."], "c": 0 },
    { "q": "Chọn câu nhân hóa:", "a": ["Dòng sông lặng lẽ chảy về biển.", "Chiếc bàn gỗ cũ.", "Ngôi nhà rộng lớn.", "Cô giáo dạy bài mới."], "c": 0 },
    { "q": "Chọn câu so sánh:", "a": ["Mặt trăng tròn như chiếc đĩa.", "Cây cao trong vườn.", "Bạn đang học bài.", "Cháu bé chơi ngoài sân."], "c": 0 },
    { "q": "Câu nào sử dụng nhân hóa?", "a": ["Gió thổi vần vũ khắp đồng ruộng.", "Bài học hôm nay khó quá.", "Bạn có đi học chưa?", "Chiếc xe chạy nhanh."], "c": 0 },
    { "q": "Câu nào sử dụng so sánh?", "a": ["Ngôi sao sáng như viên kim cương.", "Con mèo đang ngủ.", "Trời hôm nay nắng nóng.", "Quyển sách hay quá."], "c": 0 },
    { "q": "Câu nào có nhân hóa?", "a": ["Ngọn gió lùa qua cửa sổ.", "Bạn đang học bài.", "Ngôi nhà rộng lớn.", "Bài tập hôm nay khó."], "c": 0 },
    { "q": "Câu nào có so sánh?", "a": ["Hoa hồng đỏ như lửa.", "Con mèo ngủ trên ghế.", "Ngôi trường rộng rãi.", "Trời mưa to."], "c": 0 },
    { "q": "Chọn câu nhân hóa:", "a": ["Cây cối reo vui khi có gió.", "Bài tập hôm nay khó.", "Bạn có đi học không?", "Ngôi nhà cao."], "c": 0 },
    { "q": "Chọn câu so sánh:", "a": ["Cháu bé nhỏ như con thỏ.", "Ngôi trường rộng lớn.", "Mặt trời tỏa nắng.", "Bài học hôm nay dễ."], "c": 0 },
    { "q": "Câu nào là nhân hóa?", "a": ["Mặt trời chào buổi sáng.", "Bài học hôm nay dễ.", "Bạn học bài chăm chỉ.", "Chiếc bàn gỗ."], "c": 0 },
    { "q": "Câu nào là so sánh?", "a": ["Người bạn thân như anh em ruột.", "Cây cao giữa sân.", "Con mèo đang ngủ.", "Trời mưa to."], "c": 0 },
    { "q": "Câu nào có nhân hóa?", "a": ["Dòng sông vẫy tay chào mọi người.", "Bạn đang học bài.", "Ngôi nhà rộng lớn.", "Chiếc xe chạy nhanh."], "c": 0 },
    { "q": "Câu nào có so sánh?", "a": ["Trái táo đỏ như quả chín mọng.", "Con mèo đang ngủ.", "Ngôi trường rộng rãi.", "Trời hôm nay mưa to."], "c": 0 },
    { "q": "Chọn câu nhân hóa:", "a": ["Cơn mưa nhảy múa trên mái nhà.", "Chiếc bàn cũ.", "Bạn học bài chăm chỉ.", "Ngôi nhà rộng."], "c": 0 },
    { "q": "Chọn câu so sánh:", "a": ["Mặt trời như quả cầu lửa.", "Cây cao trong vườn.", "Bạn đang đọc sách.", "Trời nắng nóng."], "c": 0 },
    { "q": "Câu nào sử dụng đúng dấu ngoặc kép?", "a": ["Cô giáo nói: \"Hãy mở sách ra\".", "Tôi đi học (buổi sáng).", "Đường dẫn - đi thẳng rồi rẽ trái.", "Bạn có khỏe không?"], "c": 0 },
    { "q": "Câu nào sử dụng đúng dấu ngoặc đơn?", "a": ["Chúng tôi đi dạo (buổi chiều).", "Cô ấy nói: \"Hãy lắng nghe\".", "Xe chạy - nhanh và êm.", "Trời hôm nay nắng đẹp."], "c": 0 },
    { "q": "Câu nào sử dụng đúng dấu gạch ngang?", "a": ["Con đường này - dài và rộng - thật đẹp.", "Bạn nói: \"Hãy làm bài tập\".", "Mẹ nấu ăn (buổi tối).", "Trời hôm nay mưa to."], "c": 0 },
    { "q": "Câu nào dùng ngoặc kép đúng?", "a": ["Bố bảo: \"Học bài chăm chỉ nhé!\"", "Con mèo đang ngủ (trên ghế).", "Cây cao - đứng giữa sân - thật đẹp.", "Chúng tôi đi chơi công viên."], "c": 0 },
    { "q": "Câu nào dùng ngoặc đơn đúng?", "a": ["Quyển sách này (của em) rất hay.", "Cô giáo nói: \"Hãy lắng nghe\".", "Đường dài - quanh co - khó đi.", "Bài học hôm nay thú vị."], "c": 0 },
    { "q": "Câu nào dùng gạch ngang đúng?", "a": ["Những bông hoa - đỏ và vàng - nở rộ khắp vườn.", "Bạn nói: \"Hãy làm bài tập\".", "Chúng tôi đi dạo (buổi chiều).", "Trời hôm nay mưa to."], "c": 0 },
    { "q": "Câu nào sử dụng ngoặc kép đúng?", "a": ["Ông nói: \"Chúng ta cùng nhau học tốt nhé!\"", "Cháu bé đang chơi (ngoài sân).", "Cây xanh - tươi tốt - trong vườn.", "Bạn học bài chăm chỉ."], "c": 0 },
    { "q": "Câu nào sử dụng ngoặc đơn đúng?", "a": ["Em mang theo bút (và vở) đến lớp.", "Cô giáo nói: \"Hãy lắng nghe\".", "Con đường - dài và hẹp - khó đi.", "Trời hôm nay nắng đẹp."], "c": 0 },
    { "q": "Câu nào sử dụng gạch ngang đúng?", "a": ["Chiếc bàn - cũ và nặng - được đặt ở góc phòng.", "Bố nói: \"Hãy giúp mẹ làm việc nhà\".", "Quyển sách (của em) thật hay.", "Mẹ nấu ăn ngon."], "c": 0 },
    { "q": "Câu nào dùng ngoặc kép đúng?", "a": ["Cô bảo: \"Các em hãy chăm học\".", "Con mèo ngủ (trên ghế).", "Xe chạy - nhanh và êm - trên đường.", "Chúng tôi đi dạo."], "c": 0 },
    { "q": "Câu nào dùng ngoặc đơn đúng?", "a": ["Quyển vở (mà em mua hôm qua) đẹp lắm.", "Bố nói: \"Học bài chăm chỉ\".", "Đường - dài và hẹp - khó đi.", "Bạn chơi bóng đá."], "c": 0 },
    { "q": "Câu nào dùng gạch ngang đúng?", "a": ["Ngôi nhà - cũ kỹ nhưng chắc chắn - nằm cuối phố.", "Cô giáo nói: \"Hãy im lặng\"", "Chúng tôi đi dạo (buổi chiều).", "Trời hôm nay nắng nóng."], "c": 0 },
    { "q": "Câu nào sử dụng ngoặc kép đúng?", "a": ["Bà nói: \"Hãy ăn cơm đầy đủ\".", "Con chó ngủ (trong sân).", "Chiếc xe - đỏ và đẹp - trên đường.", "Chúng tôi đi học."], "c": 0 },
    { "q": "Câu nào sử dụng ngoặc đơn đúng?", "a": ["Bạn hãy đọc sách (từ trang 10 đến 20).", "Cô nói: \"Hãy lắng nghe\".", "Cây xanh - tươi tốt - trong vườn.", "Trời hôm nay mưa to."], "c": 0 },
    { "q": "Câu nào sử dụng gạch ngang đúng?", "a": ["Những ngọn núi - cao và hùng vĩ - trải dài khắp tầm mắt.", "Bạn nói: \"Hãy học bài\".", "Quyển sách (của em) thật hay.", "Mẹ đi chợ."], "c": 0 },
    { "q": "Câu nào dùng ngoặc kép đúng?", "a": ["Ông nói: \"Chúng ta cùng nhau làm việc tốt\"", "Cháu bé chơi (ngoài sân).", "Cây cao - đứng thẳng - trong vườn.", "Bạn học bài chăm chỉ."], "c": 0 },
    { "q": "Câu nào dùng ngoặc đơn đúng?", "a": ["Chiếc đồng hồ (mới mua) rất đẹp.", "Cô giáo nói: \"Hãy lắng nghe\".", "Xe chạy - nhanh và êm - trên đường.", "Trời hôm nay nắng đẹp."], "c": 0 },
    { "q": "Câu nào dùng gạch ngang đúng?", "a": ["Ngôi trường - rộng và sạch - nằm ở trung tâm.", "Bố nói: \"Hãy giúp mẹ\".", "Chúng tôi đi dạo (buổi chiều).", "Trời hôm nay mưa to."], "c": 0 },
    { "q": "Câu nào sử dụng ngoặc kép đúng?", "a": ["Cô bảo: \"Các em hãy học chăm chỉ\".", "Con mèo ngủ (trên ghế).", "Xe chạy - nhanh và êm - trên đường.", "Chúng tôi đi dạo công viên."], "c": 0 },
    { "q": "Câu nào sử dụng ngoặc đơn đúng?", "a": ["Quyển sách (của bạn) rất hay.", "Cô giáo nói: \"Hãy lắng nghe\"", "Cây xanh - tươi tốt - trong vườn.", "Trời hôm nay nắng đẹp."], "c": 0 },
    { "q": "Câu nào sử dụng gạch ngang đúng?", "a": ["Chiếc bàn - cũ và nặng - được đặt ở góc phòng.", "Bố nói: \"Hãy giúp mẹ làm việc nhà\"", "Chúng tôi đi dạo (buổi chiều).", "Trời hôm nay mưa to."], "c": 0 },
    { "q": "Câu nào dùng ngoặc kép đúng?", "a": ["Mẹ nói: \"Ăn cơm ngay!\"", "Con chó ngủ (trong sân).", "Chiếc xe - đỏ và đẹp - trên đường.", "Chúng tôi đi học."], "c": 0 },
    { "q": "Câu nào dùng ngoặc đơn đúng?", "a": ["Bài tập (của em) rất dễ.", "Cô giáo nói: \"Hãy lắng nghe\"", "Đường - dài và hẹp - khó đi.", "Bạn chơi bóng đá."], "c": 0 },
    { "q": "Câu nào dùng gạch ngang đúng?", "a": ["Ngọn núi - cao và hùng vĩ - trải dài khắp tầm mắt.", "Bạn nói: \"Hãy học bài\"", "Quyển sách (của em) thật hay.", "Mẹ đi chợ."], "c": 0 },
    { "q": "Câu nào sử dụng ngoặc kép đúng?", "a": ["Bà nói: \"Hãy ăn cơm đầy đủ\".", "Con chó ngủ (trong sân).", "Chiếc xe - đỏ và đẹp - trên đường.", "Chúng tôi đi học."], "c": 0 },
    { "q": "Câu nào sử dụng ngoặc đơn đúng?", "a": ["Chiếc áo (mới mua) rất đẹp.", "Cô giáo nói: \"Hãy lắng nghe\"", "Xe chạy - nhanh và êm - trên đường.", "Trời hôm nay nắng đẹp."], "c": 0 },
    { "q": "Câu nào sử dụng gạch ngang đúng?", "a": ["Ngôi nhà - cũ kỹ nhưng chắc chắn - nằm cuối phố.", "Cô giáo nói: \"Hãy im lặng\"", "Chúng tôi đi dạo (buổi chiều).", "Trời hôm nay nắng nóng."], "c": 0 },
    { "q": "Trong truyện \"Sự tích cây vú sữa\", cây vú sữa được ví với điều gì?", "a": ["Tình mẹ bao la", "Sự chăm chỉ", "Lòng dũng cảm", "Tình bạn thân thiết"], "c": 0 },
    { "q": "Nhân vật chính trong truyện \"Cây bút thần\" là ai?", "a": ["Cậu bé An", "Cô bé Mai", "Ông lão Năm", "Chú bé Tí"], "c": 0 },
    { "q": "Trong bài \"Trí thông minh của chú kiến\", chú kiến đã làm gì để cứu bạn?", "a": ["Dẫn đường thoát khỏi mưa", "Tìm thức ăn", "Xây tổ mới", "Báo cáo với mọi người"], "c": 0 },
    { "q": "Ý nghĩa câu chuyện \"Sự tích hồ Gươm\" là gì?", "a": ["Tình yêu quê hương", "Sự dũng cảm", "Lòng trung thực", "Tinh thần hợp tác"], "c": 0 },
    { "q": "Trong truyện \"Chú voi con biết vẽ\", chú voi đã học được bài học gì?", "a": ["Kiên nhẫn và sáng tạo", "Nhanh chóng và vội vàng", "Chơi bừa bãi", "Không cần cố gắng"], "c": 0 },
    { "q": "Trong bài đọc \"Bác Hồ với thiếu nhi\", Bác Hồ muốn dạy các em điều gì?", "a": ["Yêu thương và học tập chăm chỉ", "Chơi nhiều hơn học", "Chỉ nghe lời người lớn", "Làm việc nhà"], "c": 0 },
    { "q": "Trong truyện \"Con chim sẻ và bầy quạ\", con chim sẻ đã làm gì để giúp mình?", "a": ["Dùng trí thông minh tránh bầy quạ", "Chạy trốn khỏi cơn bão", "Kêu gọi bạn bè giúp đỡ", "Tìm thức ăn"], "c": 0 },
    { "q": "Ý nghĩa câu chuyện \"Sự tích bánh chưng, bánh dày\" là gì?", "a": ["Tôn trọng truyền thống và lòng hiếu thảo", "Sự giàu có", "Tinh thần dũng cảm", "Sức mạnh cá nhân"], "c": 0 },
    { "q": "Trong truyện \"Những người bạn tốt\", điều gì khiến các bạn gắn bó?", "a": ["Sự giúp đỡ và chia sẻ", "Cạnh tranh nhau", "Chơi riêng lẻ", "Chỉ học cùng nhau"], "c": 0 },
    { "q": "Trong bài đọc \"Cây tre trăm đốt\", cây tre tượng trưng cho điều gì?", "a": ["Sức mạnh và ý chí kiên cường", "Sự yếu đuối", "Sự nhỏ bé", "Tình bạn"], "c": 0 },
    { "q": "Trong truyện \"Sự tích hoa đào\", hoa đào tượng trưng cho điều gì?", "a": ["Sự may mắn và niềm vui", "Sự buồn bã", "Sự khó khăn", "Sự chia ly"], "c": 0 },
    { "q": "Trong bài đọc \"Chú gà trống và bầy gà con\", chú gà trống đã làm gì để bảo vệ gà con?", "a": ["Dẫn các con tránh nguy hiểm", "Tìm thức ăn", "Ngủ dưới mái nhà", "Chơi với gà con"], "c": 0 },
    { "q": "Ý nghĩa câu chuyện \"Sự tích con rồng cháu tiên\" là gì?", "a": ["Nêu nguồn gốc dân tộc Việt Nam", "Sự dũng cảm cá nhân", "Tình bạn thân thiết", "Sự giàu có"], "c": 0 },
    { "q": "Trong truyện \"Chú mèo ham học\", chú mèo đã học được bài học gì?", "a": ["Sự kiên trì và ham học hỏi", "Chơi nhiều hơn học", "Ngủ cả ngày", "Ăn uống đủ"], "c": 0 },
    { "q": "Trong bài đọc \"Chiếc lá cuối cùng\", hành động của chiếc lá tượng trưng cho gì?", "a": ["Hy vọng và tình bạn", "Nỗi buồn", "Sự cô đơn", "Thất bại"], "c": 0 },
    { "q": "Trong truyện \"Con dê và sư tử\", con dê đã dùng cách gì để thoát khỏi sư tử?", "a": ["Lừa sư tử bằng mưu trí", "Chạy thật nhanh", "Kêu gọi bạn bè", "Trốn trong bụi cây"], "c": 0 },
    { "q": "Ý nghĩa truyện \"Sự tích hoa mai\" là gì?", "a": ["Tình yêu quê hương và sự kiên trì", "Sự giàu sang", "Sức mạnh cá nhân", "Tình bạn"], "c": 0 },
    { "q": "Trong bài đọc \"Chú cá và bầy cá\", chú cá nhỏ học được điều gì?", "a": ["Hợp tác và đoàn kết", "Chạy nhanh hơn", "Ẩn mình một mình", "Chơi riêng"], "c": 0 },
    { "q": "Trong truyện \"Cây đa cổ thụ\", cây đa tượng trưng cho điều gì?", "a": ["Sự vững vàng và bền bỉ", "Sự yếu ớt", "Sự nhanh nhẹn", "Sự xa lạ"], "c": 0 },
    { "q": "Trong bài đọc \"Bài học từ chú ong\", chú ong dạy gì cho các em?", "a": ["Làm việc chăm chỉ và có tổ chức", "Chơi cả ngày", "Ngủ nhiều", "Chỉ quan tâm bản thân"], "c": 0 },
    { "q": "Trong truyện \"Sự tích quả dưa hấu\", quả dưa hấu tượng trưng cho gì?", "a": ["Sự may mắn và lòng nhân hậu", "Sự thông minh", "Sự dũng cảm", "Sức mạnh cá nhân"], "c": 0 },
    { "q": "Trong bài đọc \"Cây gạo của làng\", cây gạo tượng trưng cho điều gì?", "a": ["Sự che chở và tinh thần cộng đồng", "Sự buồn bã", "Sự cô đơn", "Sự yếu đuối"], "c": 0 },
    { "q": "Trong truyện \"Con chó trung thành\", chú chó làm gì để chứng tỏ sự trung thành?", "a": ["Bảo vệ chủ khi gặp nguy hiểm", "Chạy trốn", "Ăn nhiều thức ăn", "Ngủ cả ngày"], "c": 0 },
    { "q": "Ý nghĩa truyện \"Sự tích trái bưởi\" là gì?", "a": ["Tình yêu thương và biết ơn tổ tiên", "Sự dũng cảm", "Tình bạn", "Sức mạnh cá nhân"], "c": 0 },
    { "q": "Trong bài đọc \"Chú thỏ nhanh trí\", chú thỏ đã làm gì để thoát khỏi sói?", "a": ["Dùng trí thông minh đánh lừa sói", "Chạy thật nhanh", "Kêu gọi bạn bè", "Trốn trong hang"], "c": 0 },
    { "q": "Trong truyện \"Sự tích cây tre trúc\", cây tre trúc tượng trưng cho điều gì?", "a": ["Sức mạnh và ý chí kiên cường", "Sự mềm yếu", "Sự đơn độc", "Tình bạn"], "c": 0 },
    { "q": "Trong bài đọc \"Chú sóc ham ăn\", chú sóc học được bài học gì?", "a": ["Chia sẻ và biết tiết kiệm", "Ăn thật nhiều", "Ngủ cả ngày", "Chỉ quan tâm bản thân"], "c": 0 },
    { "q": "Trong truyện \"Sự tích trái mít\", trái mít tượng trưng cho điều gì?", "a": ["Lòng hiếu thảo và yêu thương gia đình", "Sức mạnh cá nhân", "Sự dũng cảm", "Tình bạn"], "c": 0 },
    { "q": "Trong bài đọc \"Chú chim sẻ thông minh\", chú chim sẻ đã làm gì để bảo vệ bản thân?", "a": ["Dùng mưu trí tránh kẻ thù", "Chạy thật nhanh", "Ẩn mình một mình", "Kêu gọi bạn bè"], "c": 0 },
    { "q": "Nước có thể tồn tại ở mấy trạng thái?", "a": ["1", "2", "3", "4"], "c": 2 },
    { "q": "Khi nước sôi ở 100°C sẽ xảy ra hiện tượng gì?", "a": ["Hóa đá", "Bay hơi", "Đóng băng", "Hóa hơi thành khí khác"], "c": 1 },
    { "q": "Khi nước ở 0°C sẽ xảy ra hiện tượng gì?", "a": ["Bay hơi", "Đóng băng", "Hóa khí", "Hóa đá"], "c": 1 },
    { "q": "Nước có khả năng hòa tan nhiều chất vì nước là chất gì?", "a": ["Đơn chất", "Dẫn điện", "Dẫn nhiệt", "Dung môi tốt"], "c": 3 },
    { "q": "Vòng tuần hoàn của nước gồm những giai đoạn nào?", "a": ["Bốc hơi, ngưng tụ, mưa, thấm vào đất", "Bốc hơi, đông đá, nóng chảy, hòa tan", "Ngưng tụ, bốc hơi, tan chảy, hòa tan", "Chảy, tan, bốc hơi, đóng băng"], "c": 0 },
    { "q": "Hiện tượng nước ngưng tụ tạo thành gì?", "a": ["Mây", "Sông", "Đá", "Cát"], "c": 0 },
    { "q": "Mưa thuộc giai đoạn nào trong vòng tuần hoàn nước?", "a": ["Bốc hơi", "Ngưng tụ", "Trôi chảy", "Hòa tan"], "c": 1 },
    { "q": "Nước biển mặn hơn nước ngọt vì lý do nào?", "a": ["Có nhiều muối hòa tan", "Có nhiều khí hòa tan", "Nhiệt độ cao hơn", "Mức nước thấp hơn"], "c": 0 },
    { "q": "Bốc hơi là quá trình nào?", "a": ["Nước chuyển từ thể lỏng sang thể khí", "Nước chuyển từ thể rắn sang thể lỏng", "Nước chuyển từ thể khí sang thể lỏng", "Nước chuyển từ thể lỏng sang thể rắn"], "c": 0 },
    { "q": "Ngưng tụ là hiện tượng nào?", "a": ["Khí nước hóa lỏng tạo thành giọt nước", "Nước hóa đá", "Nước bốc hơi thành hơi", "Nước tan vào đất"], "c": 0 },
    { "q": "Nước có tính chất gì quan trọng đối với sinh vật?", "a": ["Chứa vitamin", "Dung môi tốt", "Hóa chất độc", "Có mùi"], "c": 1 },
    { "q": "Sông, hồ, ao là nơi nào trong vòng tuần hoàn nước?", "a": ["Nguồn nước dự trữ", "Nơi bốc hơi", "Nơi ngưng tụ", "Nơi hòa tan"], "c": 0 },
    { "q": "Hơi nước trong không khí hình thành từ đâu?", "a": ["Bốc hơi từ mặt nước", "Ngưng tụ từ mây", "Tan vào đất", "Chảy thành sông"], "c": 0 },
    { "q": "Nước ở thể rắn gọi là gì?", "a": ["Hơi nước", "Đá", "Sương", "Mây"], "c": 1 },
    { "q": "Nước ở thể khí gọi là gì?", "a": ["Mưa", "Hơi nước", "Băng", "Sông"], "c": 1 },
    { "q": "Nước có thể hòa tan những chất nào?", "a": ["Muối, đường, các chất tan được", "Sắt, nhôm", "Nhựa, sỏi", "Cát, đất sét"], "c": 0 },
    { "q": "Vòng tuần hoàn nước giúp gì cho Trái Đất?", "a": ["Cung cấp nước cho sinh vật và môi trường", "Tạo ra cơn bão", "Làm lạnh Trái Đất", "Tăng mưa axit"], "c": 0 },
    { "q": "Nước biển, nước sông, nước mưa thuộc loại nước nào?", "a": ["Nước ngọt, nước mặn, nước ngọt", "Nước mặn, nước ngọt, nước mặn", "Nước mặn, nước ngọt, nước ngọt", "Nước ngọt, nước ngọt, nước mặn"], "c": 2 },
    { "q": "Mưa, sương, sương mù là kết quả của hiện tượng gì?", "a": ["Ngưng tụ", "Bốc hơi", "Đóng băng", "Hòa tan"], "c": 0 },
    { "q": "Trong vòng tuần hoàn, nước từ đất đi về đâu?", "a": ["Ra biển và hồ", "Tạo thành mây ngay trên mặt đất", "Bốc hơi và tan vào đất", "Đóng băng"], "c": 0 },
    { "q": "Nhiệt độ ảnh hưởng gì đến nước?", "a": ["Làm nước bốc hơi, đông đá, tan chảy", "Không ảnh hưởng gì", "Chỉ làm nước tan chảy", "Chỉ làm nước bay hơi"], "c": 0 },
    { "q": "Nước có vai trò gì trong đời sống hàng ngày?", "a": ["Uống, nấu ăn, tắm giặt", "Chỉ để tắm giặt", "Chỉ để trồng cây", "Chỉ để chơi"], "c": 0 },
    { "q": "Hiện tượng bốc hơi thường xảy ra ở đâu?", "a": ["Mặt hồ, sông, ao, biển", "Trong lòng đất", "Trong đá", "Trong cây"], "c": 0 },
    { "q": "Ngưng tụ thường xảy ra ở đâu?", "a": ["Không khí, tạo thành mây và sương", "Trong đá", "Trong lòng đất", "Trong sông"], "c": 0 },
    { "q": "Nước mưa thường có tính chất gì?", "a": ["Ngọt, không màu, không mùi", "Mặn, có muối", "Đục, có cát", "Đặc, màu vàng"], "c": 0 },
    { "q": "Nước giúp cây cối và sinh vật sống ra sao?", "a": ["Cung cấp dưỡng chất và tham gia phản ứng hóa học", "Không cần thiết", "Chỉ làm mát", "Chỉ làm cây đẹp hơn"], "c": 0 },
    { "q": "Quá trình nước từ biển bốc hơi lên trời gọi là gì?", "a": ["Bốc hơi", "Ngưng tụ", "Mưa", "Chảy"], "c": 0 },
    { "q": "Quá trình nước từ mây rơi xuống đất gọi là gì?", "a": ["Mưa", "Bốc hơi", "Ngưng tụ", "Hòa tan"], "c": 0 },
    { "q": "Quá trình nước từ sông, hồ ngấm xuống đất gọi là gì?", "a": ["Thấm vào đất", "Bốc hơi", "Ngưng tụ", "Mưa"], "c": 0 },
    { "q": "Không khí bao gồm những thành phần chính nào?", "a": ["Oxi, khí nitơ, khí cacbonic và hơi nước", "Oxi, khí hydro, khí heli", "Chỉ có oxi", "Chỉ có khí nitơ"], "c": 0 },
    { "q": "Tại sao con người cần không khí?", "a": ["Để thở và duy trì sự sống", "Để ăn uống", "Để đi lại", "Để ngủ"], "c": 0 },
    { "q": "Khí nào chiếm tỉ lệ lớn nhất trong không khí?", "a": ["Khí nitơ", "Oxi", "Khí cacbonic", "Hơi nước"], "c": 0 },
    { "q": "Khí oxi trong không khí có vai trò gì?", "a": ["Giúp con người và động vật thở", "Giúp cây quang hợp", "Làm nước mưa", "Tạo ra sấm sét"], "c": 0 },
    { "q": "Khí cacbonic trong không khí có nguồn gốc từ đâu?", "a": ["Hô hấp của sinh vật, cháy nhiên liệu", "Chỉ từ núi lửa", "Chỉ từ cây cối", "Chỉ từ biển"], "c": 0 },
    { "q": "Hiện tượng ô nhiễm không khí là gì?", "a": ["Không khí bị lẫn các chất độc hại", "Không khí quá lạnh", "Không khí có mây mưa", "Không khí có gió mạnh"], "c": 0 },
    { "q": "Nguyên nhân gây ô nhiễm không khí là gì?", "a": ["Khí thải từ nhà máy, xe cộ, đốt rác", "Mưa, gió", "Sương, sương mù", "Cây xanh"], "c": 0 },
    { "q": "Ô nhiễm không khí ảnh hưởng đến ai?", "a": ["Con người, động vật và cây cối", "Chỉ con người", "Chỉ động vật", "Chỉ cây cối"], "c": 0 },
    { "q": "Bảo vệ môi trường không khí bằng cách nào?", "a": ["Trồng cây, hạn chế đốt rác, sử dụng phương tiện sạch", "Để không khí tự sạch", "Đóng cửa nhà", "Đeo khẩu trang liên tục"], "c": 0 },
    { "q": "Khói bụi từ xe cộ làm gì với không khí?", "a": ["Gây ô nhiễm và độc hại", "Làm sạch không khí", "Tăng oxi", "Tăng hơi nước"], "c": 0 },
    { "q": "Chất độc trong không khí có thể gây bệnh gì cho con người?", "a": ["Bệnh hô hấp, tim mạch", "Bệnh răng", "Bệnh da đầu", "Bệnh mắt"], "c": 0 },
    { "q": "Tại sao cây xanh giúp bảo vệ không khí?", "a": ["Hấp thụ khí độc và nhả oxi", "Tạo bóng râm", "Chống gió", "Tạo cảnh quan"], "c": 0 },
    { "q": "Khí ô nhiễm thường tồn tại dưới dạng nào?", "a": ["Khí, bụi và hơi hóa chất", "Nước, băng", "Cát, sỏi", "Nhiệt độ"], "c": 0 },
    { "q": "Chúng ta giảm ô nhiễm không khí bằng cách gì khi đi lại?", "a": ["Đi xe đạp, đi bộ, dùng phương tiện công cộng", "Đi xe riêng liên tục", "Đốt rác", "Dùng xe chạy bằng xăng"], "c": 0 },
    { "q": "Khí sunfuric và nitơ oxit là gì?", "a": ["Các chất gây ô nhiễm không khí", "Các chất làm sạch không khí", "Các vitamin trong không khí", "Các chất dinh dưỡng cho cây"], "c": 0 },
    { "q": "Khí thải từ nhà máy ảnh hưởng như thế nào?", "a": ["Gây ô nhiễm không khí và mưa axit", "Làm không khí mát hơn", "Làm cây phát triển nhanh", "Tăng lượng oxi"], "c": 0 },
    { "q": "Khói bụi từ đốt rác thải nhựa gây tác hại gì?", "a": ["Gây bệnh hô hấp và độc hại cho môi trường", "Giúp không khí sạch hơn", "Tạo ra oxi", "Tăng mưa"], "c": 0 },
    { "q": "Bảo vệ không khí từ nhà trường có thể làm gì?", "a": ["Trồng cây, tiết kiệm điện, không đốt rác", "Để lớp học mở cửa liên tục", "Đốt giấy thừa", "Sử dụng xe máy nhiều"], "c": 0 },
    { "q": "Hiện tượng mù khói thường xuất hiện khi nào?", "a": ["Khi không khí bị ô nhiễm nặng", "Khi trời nắng", "Khi trời mưa", "Khi trời lạnh"], "c": 0 },
    { "q": "Sử dụng năng lượng sạch giúp bảo vệ không khí bằng cách nào?", "a": ["Giảm khí thải độc hại", "Tăng nhiệt độ không khí", "Gây ô nhiễm nước", "Tăng bụi"], "c": 0 },
    { "q": "Chúng ta nên làm gì khi trời ô nhiễm nặng?", "a": ["Đeo khẩu trang và hạn chế ra ngoài", "Đi bơi", "Tập thể dục ngoài trời", "Mở cửa nhà rộng"], "c": 0 },
    { "q": "Ô nhiễm không khí có thể gây ra hiện tượng gì cho cây trồng?", "a": ["Lá héo, cây chậm phát triển", "Cây phát triển nhanh", "Cây ra hoa nhiều hơn", "Cây xanh tốt hơn"], "c": 0 },
    { "q": "Khí thải từ phương tiện giao thông chứa gì?", "a": ["CO, CO2, NOx và bụi mịn", "Oxi, hơi nước", "Chỉ nước", "Chỉ bụi"], "c": 0 },
    { "q": "Bảo vệ không khí tại gia đình có thể làm gì?", "a": ["Hạn chế đốt rác, sử dụng năng lượng sạch, trồng cây", "Đốt than nhiều", "Mở cửa liên tục", "Dùng xe máy liên tục"], "c": 0 },
    { "q": "Khí CO trong không khí gây tác hại gì?", "a": ["Gây ngạt và hại sức khỏe con người", "Giúp thở tốt", "Tăng oxi", "Không có tác hại"], "c": 0 },
    { "q": "Vai trò của không khí đối với con người là gì?", "a": ["Giúp thở, truyền âm thanh, duy trì sự sống", "Giúp ăn uống", "Giúp di chuyển", "Giúp ngủ"], "c": 0 },
    { "q": "Một cách bảo vệ không khí khi đi học là gì?", "a": ["Đi bộ, đi xe đạp hoặc sử dụng xe công cộng", "Đốt giấy thải", "Đi xe riêng nhiều", "Sử dụng năng lượng hóa thạch"], "c": 0 },
    { "q": "Vì sao nên trồng cây ở đô thị?", "a": ["Hấp thụ khí độc và cung cấp oxi", "Chỉ để làm đẹp", "Chỉ che mưa", "Chỉ để ngăn gió"], "c": 0 },
    { "q": "Bảo vệ môi trường không khí có ích lợi gì?", "a": ["Giúp con người và sinh vật sống khỏe mạnh", "Chỉ giúp cây phát triển", "Chỉ giúp nước sạch", "Không có ích lợi"], "c": 0 },
];

